<div class="uploadFileYandex">
	<div class="movie">
		<?php if(!$this->data['data']['yandex_movie']):?>
			<form  action="<?=BASE_URL.'/index/controlyandexdisk' ?>" method="post" enctype="multipart/form-data">
				<ul>
					<li><input  name="uploadFileYandex[movie]" type="file"></li>
					<li><input type="submit" name="uploadFileYandex[submit][movie]" value="загрузить"></li>
				</ul>
			</form>
		<?php else: ?>
			<span><a href="<?=BASE_URL.'/index/uploadfileyandex/dir/movie/fileName/'.$this->data['data']['yandex_movie']?>/user_name/<?=$this->data['data']['name']?>">скачать</a>&nbsp;&nbsp;
				<a href="<?=BASE_URL.'/index/deletefileyandex/dir/movie/fileName/'.$this->data['data']['yandex_movie']?>">удалить</a></span></span>
		<?php endif; ?>
		<!--		<div>Только видео формат!</div>-->
	</div>
	<div class="audio">
		<?php if(!$this->data['data']['yandex_audio']):?>
			<form  action="<?=BASE_URL."/index/controlyandexdisk" ?>" method="post" enctype="multipart/form-data">
				<ul>
					<li><input  name="uploadFileYandex[audio]" type="file"></li>
					<li><input type="submit" name="uploadFileYandex[submit][audio]" value="загрузить"></li>
				</ul>
			</form>
		<?php else: ?>
			<span><a href="<?=BASE_URL.'/index/uploadfileyandex/dir/audio/fileName/'.$this->data['data']['yandex_audio']?>/user_name/<?=$this->data['data']['name']?>">скачать</a>&nbsp;&nbsp;
				<a href="<?=BASE_URL.'/index/deletefileyandex/dir/audio/fileName/'.$this->data['data']['yandex_audio']?>">удалить</a></span>
		<?php endif; ?>
		<!--		<div>Только аудио формат!</div>-->
	</div>
	<div class="clear"></div>
</div>
