<div class="clear"></div>
<div class="footer-wrapper">
	<div class="footer-container">
		<div class="footer-box clearfix">
			<div id="footer" class="footer wrapper-3-row">
				<div class="section clearfix">
					<div class="region region-footer-a">
						<div id="block-block-7" class="block block-block footer-contacts-block clearfix">
							<div class="content">
								<div class="footer-adress-wrapper">220017, Республика Беларусь,<br>
									г. Минск, ул. Дунина-Марцинкевича 2/1 оф.206
								</div>
								<div class="footer-phones-wrapper"><span class="footer-phone-wrapper">+375 29 <strong>678
											32 35</strong></span><span class="footer-phone-wrapper">+375 17 <strong>202
											21 52</strong></span></div>
								<div class="footer-mail-wrapper"><a
										href="mailto:info@proconsult.by">info@proconsult.by</a><br>
									_____________________________________________
									<p>Разработка сайта - <a href="http://ib.by/">ib.by</a></p></div>
							</div>
						</div>
					</div>
					<div class="region region-footer-b">
						<div id="block-block-8" class="block block-block footer-social-block cleafix">
							<h2>Мы в социальных сетях:</h2>

							<div class="content">
								<div>
									<a href="https://twitter.com/ProconsultBy" class="social-link social-link-twitter">Twitter</a><a
										href="https://www.facebook.com/Proconsult.by?ref=hl&ref_type=bookmark"
										class="social-link social-link-facebook">Facebook</a><a
										href="https://vk.com/proconsult" class="social-link social-link-vkontakte">ВКонтакте</a><a
										href="https://www.youtube.com/channel/UCOfQ7LhG7TDH32txjVNicPg/videos"
										class="social-link social-link-youtube">Youtube</a>
								</div>
							</div>
						</div>
					</div>
					<div class="region region-footer-c">
						<div id="block-block-15" class="block block-block footer-info-block clearfix">
							<h2>Информация:</h2>

							<div class="content">
								<div class="info-links-wrapper">
									<div class="link-box"><a href="http://www.proconsult.by/statyi" class="info-link"
															 alt="">Статьи</a></div>
									<div class="link-box"><a href="http://www.proconsult.by/vopros-otvet"
															 class="info-link" alt="">Вопрос-ответ</a></div>
									<div class="link-box"><a href="http://www.proconsult.by/publichnaya-oferta"
															 class="info-link" alt="">Публичная оферта</a></div>
									<div class="link-box"><a href="http://www.proconsult.by/trenery" class="info-link"
															 alt="">Тренеры</a></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>