<div class="page-wrapper" id="page-wrapper">
	<div class="page" id="page">
		<!-- header -->
		<div class="header-wrapper" id="header">
			<div class="section clearfix">

				<div id="logo-and-slogan" class="logo-and-slogan-wrapper">
					<div class="logo-wrapper site-logo">
						<a href="http://proconsult.by/" title="Главная" rel="home" id="logo">
							<img src="http://proconsult.by/sites/all/themes/pro_consult/logo.png" alt="Главная"/>
						</a>
					</div>
					<div class="slogan-wrapper">
						<div id="site-slogan">
							Бизнес-обучение и подбор персонала в РБ и РФ
						</div>
					</div>
					<!-- /.slogan-wrapper -->
				</div>
				<div id="header_section" class="h_section section clearfix">
					<div class="region region-header">
						<div id="block-block-4" class="block block-block order-btns-block">
							<div class="content">
								<div class="order-call-btn-wrapper">
									<a href="http://proconsult.by/node/11?height=500&amp;width=600" class="colorbox-node order-call-btn header-btn">Обратный звонок</a>
								</div>
								<div class="offer-btn-wrapper">
									<a href="http://proconsult.by/node/12?height=450&amp;width=600" class="colorbox-node offer-btn header-btn">Коммерческое <span>предложение</span></a>
								</div>
							</div>
						</div>
						<div id="block-block-5" class="block block-block header-contacts-block">
							<div class="content">
								<div class="header-adress-wrapper">220017, Республика Беларусь,<br/>
									г. Минск, ул. Дунина-Марцинкевича 2/1 оф.206
								</div>
								<div class="header-phones-wrapper">
									<span class="header-phone-wrapper">+375 29 <strong>678 32 35</strong></span>
									<span class="header-phone-wrapper">+375 17 <strong>202 21 52</strong></span>
								</div>
								<div class="header-mail-wrapper">
									<a href="mailto:info@proconsult.by">info@proconsult.by</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="main-menu" class="main-menu">
				<div class="section clearfix">
					<div class="region region-main-menu">
						<div id="block-nice-menus-1" class="block block-nice-menus main-menu-block">
							<div class="content">
								<ul class="nice-menu nice-menu-down nice-menu-main-menu nice-menus-processed sf-js-enabled sf-arrows"
									id="nice-menu-1">
									<li class="menu-224 menu-path-front first odd">
										<a href="http://proconsult.by/" onclick="return confirm('Вы действительно '+'хотите' +' покинуть страницу!')?true:false" title="" class="active">Вернуться к сайту</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="clear"></div>