<main class="resume">
<?php if($this->data['data']['admin']): ?>
	<div class="resume_header">
		<p>
			<a class="header_back" href="<?=BASE_URL.'/admincontrol'?>">панель управления</a>
			<a class="out" href='<?=BASE_URL."/admin/out/"?>'>Выход</a>

		<div class="clear"></div>
		</p>
	</div>
	<div class="favorite">
		<p class="header_favorite"><img src='<?=BASE_URL."/public/img/favorite.png"?>'>Добавить в отобранные</p>
		<div id="favorite_folds">
			<p class="myFolders">МОИ ПАПКИ</p>
			<ul id="checkbox_list"></ul>
			<p class="addFolders">СОЗДАТЬ ПАПКУ</p>
			<input type="checkbox"  value="new_folder" id="new_checkbox" disabled>
			<input id="input_text" type="text" placeholder="Новая папка">
			<div class="clear"></div>
			<button id='button'>сохранить</button>
			<img id="ajax_loader" src="<?=BASE_URL.'/public/img/ajax-loader.gif'?>">
		</div>
	</div>
	<div class="print">
		<p>
			<a href="<?= BASE_URL . "/print/index/id/{$this->data['data']['id_user']}" ?>"><img
					src='<?= BASE_URL . "/public/img/print.png" ?>'>Распечатать</a>
		</p>
	</div>
	<div class="print" id="download">
		<p class="active_download">
			<img src='<?= BASE_URL . "/public/img/download.png" ?>'>Скачать резюме
		</p>

		<div data-id-user="<?= $this->data['data']['id_user'] ?>" id="download_content">
			<?php if (count($this->data['data']['comments'])): ?>
				<p><input type="checkbox" id="without_comments" value="comments">Без комментариев</p>
			<?php endif; ?>
			<?php if (!empty($this->data['data']['conclusion'])): ?>
				<p><input type="checkbox" id="without_conclusion" value="conclusion">Без заключения</p>
			<?php endif; ?>
			<p>
				<button id="button">Скачать</button>
			</p>
		</div>
	</div>
	<?php if($this->data['data']['admin'] === 'main'): ?>
		<div class="print" id="download">
			<p class="active_download">
				<a  onclick="return confirm('Вы действительно хотите удалить резюме?')?true:false" href="<?=BASE_URL.'/index/delete'?>"><img src='<?= BASE_URL . "/public/img/delete_resume.png" ?>'>удалить резюме</a>
			</p>
		</div>
	<?php endif ?>
	<div class="clear"></div>
<?php else: ?>
	<h1>Создать резюме за несколько минут</h1>
<?php endif; ?>
<div class="resume_data_left">
<section class="photo_personal_contacts">
	<div class="right">
		<?php if($this->data['data']['photo'] === 'no-photo.png'): ?>
			<a class="addPhoto" href='<?=BASE_URL.'/profile/photo'?>'><span>Фото</span><br><span>Добавить...</span></a>
		<?php else: ?>
			<figure>
				<p><a href="<?=BASE_URL.'/profile/photo'?>"><img src="<?=BASE_URL.'/files/photo/' .$this->data['data']['photo']?>" alt="" ></a></p>
			</figure>
		<?php endif ?>
	</div>
	<div class="left">
		<?php if(!$this->data['data']['name']): ?>
			<div class='add'>
				<a href="<?=BASE_URL.'/profile/personal'?>"><span>Имя, возраст, город</span><span>Добавить...</span></a>
			</div>
		<?php else: ?>
			<div class="personal_data">
				<header>
					<h1><a href='<?=BASE_URL.'/profile/personal'?>'>
							<?php if($this->data['data']['admin'] === 'manager'): ?>
								<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
							<?php else: ?>
								<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
							<?php endif; ?>
						</a>
					</h1>
					<h2><?=$this->data['data']['name']?></h2>
				</header>
				<section>
					<p><?=$this->data['data']['birth_sex_city_move_trip']?></p>
					<p><?=$this->data['data']['auto']?></p>
				</section>
			</div>
		<?php endif?>
		<div class="contacts_data">
			<?php if(!$this->data['data']['call_me']): ?>
				<div class='add'>
					<a href='<?=BASE_URL.'/profile/contacts'?>'><span>Контакты</span><span>Добавить...</span></a>
				</div>
			<?php else: ?>
				<h1>
					<a href='<?=BASE_URL.'/profile/contacts'?>'>
						<?php if($this->data['data']['admin'] === 'manager'): ?>
							<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
						<?php else: ?>
							<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
						<?php endif; ?>
					</a>
				</h1>
				<section>
					<?=$this->data['data']['call_me']?>
				</section>
			<?php endif; ?>
		</div>
	</div>
</section>
<div class="clear"></div>
<div class="salary_position">
	<?php if(!$this->data['data']['desired_position']): ?>
		<div class="salary_position_add">
			<a href='<?=BASE_URL.'/side/position'?>'><span>Желаемая должность и зарплата</span><span>Добавить...</span></a>
		</div>
	<?php else: ?>
		<header>
			<h1>Желаемая должность и зарплата
				<a href='<?=BASE_URL.'/side/position'?>'>
					<?php if($this->data['data']['admin'] === 'manager'): ?>
						<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
					<?php else: ?>
						<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
					<?php endif; ?>
				</a></h1>
		</header>
		<p><strong><?=$this->data['data']['desired_position']?></strong></p>
		<p><strong><?=$this->data['data']['salary']?></strong></p>
		<p><?=$this->data['data']['professional_area']?></p>
		<p><?=$this->data['data']['employment']?></p>
		<p><?=$this->data['data']['schedule']?></p>
	<?php endif; ?>
</div>

<div class="experience">
	<?php if(is_null($this->data['data']['no_experience'])): ?>
		<div class="experience_add">
			<a href='<?=BASE_URL.'/side/experience'?>'><span>Опыт работы</span><span>Добавить...</span></a>
		</div>
	<?php else: ?>
		<section>
			<h1>
				Опыт работы <?=$this->data['data']['sum_experience']?><a href='<?=BASE_URL.'/side/experience'?>'>
					<?php if($this->data['data']['admin'] === 'manager'): ?>
						<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
					<?php else: ?>
						<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
					<?php endif; ?>
				</a>
			</h1>
			<?=$this->data['data']['experience_organizations']?>
			<div class="skills">
				<h2>
					Ключевые навыки<a href='<?=BASE_URL.'/side/experience#skill'?>'>
						<?php if($this->data['data']['admin'] === 'manager'): ?>
							<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
						<?php else: ?>
							<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
						<?php endif; ?>
					</a>
				</h2>
				<p>
					<?=$this->data['data']['experience_key_skills']?>
				</p>
			</div>

			<div class="left_40">
				<h2>
					Обо мне<a href='<?=BASE_URL.'/side/experience#ab_self'?>'>
						<?php if($this->data['data']['admin'] === 'manager'): ?>
							<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
						<?php else: ?>
							<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
						<?php endif; ?>
					</a>
				</h2>
				<p>
					<?=$this->data['data']['experience_about_self']?>
				</p>
			</div>

			<div class="right_60">
				<h2>
					Рекомендации<a href='<?=BASE_URL.'/side/experience#reg'?>'>
						<?php if($this->data['data']['admin'] === 'manager'): ?>
							<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
						<?php else: ?>
							<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
						<?php endif; ?>
					</a>
				</h2>
				<?=$this->data['data']['experience_recommend']?>
			</div>
			<div class="clear"></div>
		</section>
	<?php endif; ?>
</div>

<div class="education_language">
	<?php if(!$this->data['data']['institutions']): ?>
		<div class="education_add">
			<a href='<?=BASE_URL.'/side/education'?>'><span>Образование</span><span>Добавить...</span></a>
		</div>
	<?php else: ?>
		<section>
			<h1>
				Образование<a href='<?=BASE_URL.'/side/education'?>'>
					<?php if($this->data['data']['admin'] === 'manager'): ?>
						<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
					<?php else: ?>
						<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
					<?php endif; ?>
				</a>
			</h1>
			<?=$this->data['data']['institutions']?>
			<div class="languages">
				<h2>Знание языков <a href='<?=BASE_URL.'/side/education#lang'?>'>
						<?php if($this->data['data']['admin'] === 'manager'): ?>
							<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
						<?php else: ?>
							<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
						<?php endif; ?>
					</a></h2>
				<?=$this->data['data']['languages']?>
			</div>
			<?php if($this->data['data']['courses_names']): ?>
				<div class="courses">
					<h2>Повышение квалификации, курсы <a href='<?=BASE_URL.'/side/education#cours'?>'>
							<?php if($this->data['data']['admin'] === 'manager'): ?>
								<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
							<?php else: ?>
								<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
							<?php endif; ?>
						</a></h2>
					<?=$this->data['data']['courses_names']?>
				</div>
			<?php endif; ?>
			<?php if($this->data['data']['tests_exams_names']): ?>
				<div class="courses">
					<h2>Тесты, экзамены <a href='<?=BASE_URL.'/side/education#tests'?>'>
							<?php if($this->data['data']['admin'] === 'manager'): ?>
								<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
							<?php else: ?>
								<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
							<?php endif; ?>
						</a></h2>
					<?=$this->data['data']['tests_exams_names']?>
				</div>
			<?php endif; ?>
			<?php if($this->data['data']['electronic_certificates_names']): ?>
				<div class="courses">
					<h2>Электронные сертификаты <a href='<?=BASE_URL.'/side/education#sert'?>'>
							<?php if($this->data['data']['admin'] === 'manager'): ?>
								<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
							<?php else: ?>
								<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
							<?php endif; ?>
						</a></h2>
					<?=$this->data['data']['electronic_certificates_names']?>
				</div>
			<?php endif; ?>
		</section>
	<?php endif; ?>
</div>

<?php if($this->data['data']['name']): ?>
	<div class="nationality_workpermit">
		<header>
			<h1>Гражданство, время в пути до работы<a href='<?=BASE_URL.'/profile/personal#nat'?>'>
					<?php if($this->data['data']['admin'] === 'manager'): ?>
						<img src="<?=BASE_URL.'/public/img/view.png'?>">смотреть
					<?php else: ?>
						<img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать
					<?php endif; ?>
				</a></h1>
		</header>
		<?=$this->data['data']['nationality_work_permit']?>
	</div>
<?php endif; ?>
</div>
<div class="resume_widget">
	<?=$this->data['helpers']['widget']?>
</div>
<div class="clear"></div>
<?php if(!empty($this->data['data']['admin'])): ?>
	<div class="conclusion" id="concl">
		<?php if( empty($this->data['data']['conclusion']) ): ?>
			<h1>Заключение</h1>
			<form  action="<?=BASE_URL."/index/conclusion" ?>" method="post">
				<textarea class='conclusion_textarea' name="conclusion"></textarea>
				<input class="button_conclusion" type="submit" name="updateConclusion" value="сохранить">
			</form>
			<div class="clear"></div>
		<?php  else: ?>
			<h1>Заключение <span class="editConclusion"><img src="<?=BASE_URL.'/public/img/edit.png'?>">редактировать</span>
				<span class="deleteConclusion"><a href="<?=BASE_URL.'/index/conclusion/delete/true'?>"><img src="<?=BASE_URL .'/public/img/delete.png'?>">удалить</a></span></h1>
			<div class="conclusion_text"><?=$this->data['data']['conclusion']?></div>
			<div class="clear"></div>
		<?php endif; ?>
	</div>
<?php endif; ?>
</main>