<main class="personal contacts">
	<article>
		<div class="arrow-right"></div>
		<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме без сохранения</a>
		<div class="clear"></div>
		<section>
			<h1>Контакты</h1>
			<div class="form">
				<form  action='<?=BASE_URL.'/profile/contacts'?>' id="personal_contacts" method="post">
					<table>
						<tbody>
						<tr>
							<td><label for="mobile_phone">Мобильный телефон</label></td>
							<td>+</td>
							<td><input type="tel"  id="mobile_phone"  name="mobile_phone"
							           value='<?=$this->data['data']['inputs']['mobile_phone']['value']?>'></td>
							<td><input type="radio" name="preferred_communication"
									<?php if ($this->data['data']['inputs']['preferred_communication']['value'] == 1)echo'checked'?> value='1'>Желаемый вид связи</td>
							<td class="message"><span class="required"><?=$this->data['data']['inputs']['mobile_phone']['val']['message']?></span></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td  class="comment" colspan="3">
								Комментарий<br><input type="text" name="comment_mobile_phone" value='<?=$this->data['data']['inputs']['comment_mobile_phone']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="home_phone">Домашний телефон</label></td>
							<td>+</td>
							<td><input type="tel"  id="home_phone"  name="home_phone" value='<?=$this->data['data']['inputs']['home_phone']['value']?>'></td>
							<td><input type="radio" name="preferred_communication"
									<?php if ($this->data['data']['inputs']['preferred_communication']['value'] == 2)echo'checked'?> value='2'>Желаемый вид связи</td>
							<td class="message"><span class="required hidden"><span class="required"><?=$this->data['data']['inputs']['home_phone']['val']['message']?></span></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td class="comment" colspan="3">
								Комментарий<br>
								<input type="text" name="comment_home_phone" value='<?=$this->data['data']['inputs']['comment_home_phone']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="work_phone">Рабочий телефон</label></td>
							<td>+</td>
							<td><input type="tel"  id="work_phone" name="work_phone" value='<?=$this->data['data']['inputs']['work_phone']['value']?>'></td>
							<td><input type="radio" name="preferred_communication"
									<?php if ($this->data['data']['inputs']['preferred_communication']['value'] == 3)echo'checked'?> value='3'>Желаемый вид связи</td>
							<td class="message"><span class="required"><span
										class="required"><?=$this->data['data']['inputs']['work_phone']['val']['message']?></span></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td  class="comment" colspan="4">
								Комментарий<br><input type="text" name="comment_work_phone" value='<?=$this->data['data']['inputs']['comment_work_phone']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="email">Эл. почта<span class="required">*</span></label></td>
							<td></td>
							<td><input type="email"  id="email" name="email"
							           value='<?=$this->data['data']['inputs']['email']['value']?>'></td>
							<td><input type="radio" name="preferred_communication"
									<?php if ($this->data['data']['inputs']['preferred_communication']['value'] == 4)echo'checked'?> value='4'>Желаемый вид связи</td>
							<td class="message"><span class="required"><?=$this->data['data']['inputs']['email']['val']['message']?></span></td>
						</tr>
						<tr>
							<td><label for="icq">ICQ</label></td>
							<td><img src="<?=BASE_URL?>/public/img/icq.png"></td>
							<td colspan="3"><input type="text" id="icq" name="icq"
							                       value='<?=$this->data['data']['inputs']['icq']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="skype">Skype</label></td>
							<td><img src="<?=BASE_URL?>/public/img/skype.png"></td>
							<td colspan="3"><input type="text" id="skype" name="skype"
							                       value='<?=$this->data['data']['inputs']['skype']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="free_lance">Free-lance</label></td>
							<td><img src="<?=BASE_URL?>/public/img/freelance.png"></td>
							<td colspan="3"><input type="text" id="free_lance" name="free_lance"
							                       value='<?=$this->data['data']['inputs']['free_lance']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="my_circle">Мой круг</label></td>
							<td><img src="<?=BASE_URL?>/public/img/moykrug.png"></td>
							<td colspan="3"><input type="text" id="my_circle" name="my_circle"
							                       value='<?=$this->data['data']['inputs']['my_circle']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="linkedln">Linkedln</label></td>
							<td><img src="<?=BASE_URL?>/public/img/linkedin.png"></td>
							<td colspan="3"><input type="text" id="linkedln" name="linkedln"
							                       value='<?=$this->data['data']['inputs']['linkedln']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="facebook">Facebook</label></td>
							<td><img src="<?=BASE_URL?>/public/img/facebook.png"></td>
							<td colspan="3"><input type="text" id="facebook" name="facebook"
							                       value='<?=$this->data['data']['inputs']['facebook']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="live_journal">LiveJournal</label></td>
							<td><img src="<?=BASE_URL?>/public/img/livejournal.png"></td>
							<td colspan="3"><input type="text" id="live_journal" name="live_journal"
							                       value='<?=$this->data['data']['inputs']['live_journal']['value']?>'>
							</td>
						</tr>
						<tr>
							<td><label for="other_site">Другой сайт</label></td>
							<td></td>
							<td colspan="3"><input type="text"  id="other_site" name="other_site"
							                       value='<?=$this->data['data']['inputs']['other_site']['value']?>'></td>
						</tr>
						</tbody>
						<tfoot>
						<tr>
							<td colspan="5">
								<div class="contacts_footer">
									<input type="submit"  name="saveContacts" value="Сохранить">
									<a class="back" href="<?=BASE_URL?>">Отмена</a>
								</div>
							</td>
						</tr>
						</tfoot>
					</table>
				</form>
			</div>
		</section>
	</article>
</main>