<main class="resume">
	<article>
		<h1>Создать резюме за несколько минут</h1>
		<section class="foto_fio">
			<a class="addFoto" href="#1"><span>Фото</span><br><span>Добавить...</span></a>
			<div class="addFio">
				<a href="#2"><span>Имя, возвраст, город</span><span>Добавить...</span></a>
				<a href="#3"><span>Контакты</span><span>Добавить...</span></a>
			</div>
			<div class="clear"></div>
			<aside class="side">
				<a href="#4"><span>Желаемая должность и зарплата</span><span>Добавить...</span></a>
				<a href="#5"><span>Образование</span><span>Добавить...</span></a>
				<a href="#6"><span>Опыт работы</span><span>Добавить...</span></a>
			</aside>
			<aside class="end_resume">
				<a href="">Закончить заполение анкеты</a>
			</aside>
		</section>
	</article>
</main>