<main class="personal">
	<article>
		<div class="arrow-right"></div>
		<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме</a>
		<div class="clear"></div>
		<section>
			<h1>Персональная информация</h1>
			<div class="form">
				<form  action='<?=BASE_URL.'/profile/personal'?>' id="personal_form" method="post">
					<table>
						<tbody>
						<tr>
							<td><label for="surname">Фамилия<span class="required input">Обязательно для заполнения</span></label></td>
							<td>
								<input type="text"  id="surname" name="surname" value='<?=htmlspecialchars($this->data['data']['inputs']['surname']['value'],ENT_QUOTES)?>'>
								<div class="message"><span class="required"><?=$this->data['data']['inputs']['surname']['val']['message']?></span></div>
							</td>
						</tr>
						<tr>
							<td><label for="first_name">Имя<span class="required input">Обязательно для заполнения</span></label></td>
							<td>
								<input type="text" name="first_name" value='<?=htmlspecialchars($this->data['data']['inputs']['first_name']['value'],ENT_QUOTES)?>'>
								<div class="message"><span class="required"><?=$this->data['data']['inputs']['first_name']['val']['message']?></span></div>
							</td>
						</tr>
						<tr>
							<td><label for="patronymic">Отчество</label></td>
							<td>
								<input type="text" id="patronymic" name="patronymic" value='<?=htmlspecialchars($this->data['data']['inputs']['patronymic']['value'],ENT_QUOTES)?>'>
								<div class="message"><span class="required"><?=$this->data['data']['inputs']['patronymic']['val']['message']?></span></div>
							</td>
						</tr>
						<tr>
							<td>Дата рождения</td>
							<td>
								<span id="birth">
									<select id="day_birth" name="day_birth">
										<option value=''></option>
										<?php for($i=1; $i <= 31; $i++): ?>
											<option value='<?=$i?>'<?php if($this->data['data']['inputs']['birth']['day_birth']==$i)echo'selected'?>><?=$i?></option>
										<?php endfor; ?>
									</select>
									<select id="month_birth" name="month_birth">
										<option value=""></option>
										<?php
										foreach(array(1=>"январь",
													2=>"февраль",
													3=>"март",
													4=>"апрель",
													5=>"май",
													6=>"июнь",
													7=>"июль",
													8=>"август",
													9=>"сентябрь",
													10=>"октябрь",
													11=>"ноябрь",
													12=>"декабрь") as $key => $month):?>
											<option value='<?=$key?>'<?php if($this->data['data']['inputs']['birth']['month_birth']==$key)
												echo'selected'?>><?=$month?></option>
										<?php endforeach; ?>
									</select>
									<select id="year_birth" name="year_birth">
										<option value=""></option>
										<?php for($i=(date('Y')-14); $i >= 1900; --$i): ?>
											<option value='<?=$i?>'<?php if($this->data['data']['inputs']['birth']['year_birth']==$i)echo'selected'?>><?=$i?></option>
										<?php endfor; ?>
									</select>
								</span>
								<div class="data">
									<div class="message"><span class="required"><?=$this->data['data']['inputs']['birth']['val']['message']?></span></div>
								</div>
							</td>
						</tr>
						<tr>
							<td>Пол</td>
							<td>
								<input type="radio" name="sex" value="Мужской" <?php if($this->data['data']['inputs']['sex']['value'] === 'Мужской' ||
									!$this->data['data']['inputs']['sex']['value']) echo 'checked'?>>Мужской<br>
								<input type="radio" name="sex" value="Женский" <?php if($this->data['data']['inputs']['sex']['value'] === 'Женский') echo 'checked' ?>>Женский
							</td>
						</tr>
						<tr>
							<td><label for="city">Город проживания<span class="required input">Обязательно для заполнения</span></label></td>
							<td>
								<input name="city" id="city" type="text" value='<?=htmlspecialchars($this->data['data']['inputs']['city']['value'],ENT_QUOTES)?>'>
								<p class="example">Например: <span id="city_example">Минск</span></p>
								<div class="message"><span class="required"><?=$this->data['data']['inputs']['city']['val']['message']?></span></div>
							</td>
						</tr>
						<tr>
							<td>Переезд</td>
							<td>
								<input type="radio" name="move" value="Невозможен" <?php if($this->data['data']['inputs']['move']['value'] === 'Невозможен' || !$this->data['data']['inputs']['move']['value']) echo 'checked'?>>Невозможен<br>
								<input type="radio" name="move" value="Возможен" <?php if($this->data['data']['inputs']['move']['value'] === 'Возможен') echo 'checked' ?>>Возможен<br>
								<input type="radio" name="move" value="Желателен"  <?php if($this->data['data']['inputs']['move']['value'] === 'Желателен') echo 'checked' ?>>Желателен
							</td>
						</tr>
						<tr>
							<td>Готовность к командировкам</td>
							<td>
								<input type="radio" name="trip" value="Никогда" <?php if ($this->data['data']['inputs']['trip']['value'] === 'Никогда' ||
									!$this->data['data']['inputs']['trip']['value']) echo 'checked'?>>Никогда<br>
								<input type="radio" name="trip" value="Готов" <?php if($this->data['data']['inputs']['trip']['value'] === 'Готов') echo 'checked' ?>>Готов<br>
								<input type="radio" name="trip" value="Иногда" <?php if($this->data['data']['inputs']['trip']['value'] === 'Иногда') echo 'checked' ?>>Иногда
							</td>
						</tr>
						<tr id="nat">
							<td><label for="nationality">Гражданство</label></td>
							<td>
								<input type="text" id="nationality" name="nationality" value='<?=htmlspecialchars($this->data['data']['inputs']['nationality']['value'],ENT_QUOTES)?>'>
								<p  class="example">Например: <span id="nationality_example">Беларусь</span></p>
							</td>
						</tr>
						<tr>
							<td><label for="work_permit">Разрешение на работу</label></td>
							<td>
								<input type="text" id="work_permit" name="work_permit" value='<?=htmlspecialchars($this->data['data']['inputs']['work_permit']['value'],ENT_QUOTES)?>'>
								<p  class="example">Например: <span id="work_permit_example">Беларусь</span></p>
							</td>
						</tr>
						<tr>
							<td>Желательное время в пути до работы</td>
							<td>
								<input type="radio" name="travel_time_work" value="Не имеет значения" <?php if($this->data['data']['inputs']['travel_time_work']['value'] === 'Не имеет значения'|| !$this->data['data']['inputs']['travel_time_work']['value']) echo 'checked'?>>Не имеет значения<br>
								<input type="radio" name="travel_time_work" value="Не более часа"  <?php if($this->data['data']['inputs']['travel_time_work']['value'] === 'Не более часа') echo 'checked' ?>>Не более часа<br>
								<input type="radio" name="travel_time_work" value="Не более полутора часов"  <?php if($this->data['data']['inputs']['travel_time_work']['value'] === 'Не более полутора часов') echo 'checked' ?>>Не более полутора часов
							</td>
						</tr>
						<tr>
							<td>Наличие авто</td>
							<td><input type="checkbox" name="auto" value="есть" <?php if($this->data['data']['inputs']['auto']['value'] === 'есть') echo 'checked'?>></td>
						</tr>
						<tr>
							<td>Наличие водительского удостоверения</td>
							<td><input type="checkbox" name="certificate_auto" value="есть"
									<?php if($this->data['data']['inputs']['certificate_auto']['value'] === 'есть') echo 'checked' ?>></td>
						</tr>
						</tbody>
						<tfoot>
						<?php if($this->data['data']['admin'] !== 'manager'): ?>
							<tr>
								<td colspan="2">
									<div class="data_f">Проверьте поле: Дата рождения</div>
									<div>
										<input type="submit" id="submitPersonal"  name="savePersonal" value="Сохранить">
										<a class="back" href="<?=BASE_URL?>">Отмена</a>
									</div>
								</td>
							</tr>
						<?php endif; ?>
						</tfoot>
					</table>
				</form>
			</div>
		</section>
	</article>
</main>