<main class="photo">
	<article>
		<div class="arrow-right"></div>
		<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме без сохранения</a>
		<div class="clear"></div>
		<section>
			<h1>Фотография</h1>
			<div class="message_error_uploads_photo"></div>
			<div class="user_photo">Без фото</div>
			<div class="photo_form">
				<form  action='<?=BASE_URL."/profile/uploads"?>' method="post" enctype="multipart/form-data">
					<label for="file">Загрузить фотографию<br>jpg, gif, png, bmp, не более 6Mб</label>
					<input type="hidden" name="MAX_FILE_SIZE" value="6000" />
					<input type="file" id="file">
					<input type="submit" id="submit_download" value="Загрузить">
					<div class="clear"></div>
					<div class="save">
						<div class="center">
							<input type="submit" value="Сохранить">
							<a class="back" href="<?=BASE_URL?>">Отмена</a>
						</div>
					</div>
				</form>
			</div>
		</section>
	</article>
</main>
