<main class="photo">
	<article>
		<div class="arrow-right"></div>
		<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме</a>
		<div class="clear"></div>
		<section>
			<form  action='<?=BASE_URL."/profile/photo"?>' method="post" enctype="multipart/form-data">
				<h1>Фотография</h1>
				<div class="user_photo"><img src=<?php if(isset($this->data['data']['src']))
						echo "{$this->data['data']['src']}"; else echo BASE_URL."/public/img/no-photo.png"?>></div>
				<?php foreach($this->data['helpers'] as $helper)echo $helper?>
				<div class="clear"></div>
				<div class="photo_form">
					<label for="file">Загрузить фотографию<br>jpg, gif, png, bmp, не более 6Mб</label>
					<input type="hidden" name="MAX_FILE_SIZE" value="6291456" />
					<input type="file" name="photo" max="1" id="file">
					<input type="submit" id="submit_download" name="submit_download" value="Загрузить">
					<div class="clear"></div>
				</div>
			</form>
		</section>
	</article>
</main>
