<main class="photo">
	<article>
		<div class="arrow-right"></div>
		<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме</a>
		<div class="clear"></div>
		<section>
			<form  action='<?=BASE_URL."/profile/photo"?>' method="post" enctype="multipart/form-data">
				<h1>Фотография</h1>
				<div class="user_photo">
					<img src='<?=BASE_URL.$this->data['data']['src']?>'>
				</div>
				<?php if($this->data['data']['admin'] !== 'manager'): ?>
				<?php foreach($this->data['helpers'] as $helper)echo $helper?>
				<div class="photo_form">
					<?php if($this->data['data']['submit']): ?>
					<div class="clear"></div>
					<label for="file">Загрузить фотографию<br>jpg, gif, png, bmp, не более 6Mб</label>
					<input type="hidden" name="MAX_FILE_SIZE" value="6291456" />
					<input type="file" name="photo" max="1" id="file" accept="image/jpeg,image/png">
					<input type="submit" id="submit_download" name="submit_download" value="Загрузить">
				</div>
				<div class="clear"></div>
			<?php else: ?>
				<div  class="delete_photo">
					<a href='<?=BASE_URL."/profile/delete/id{$this->data['data']['src']}"?>'>удалить</a>
				</div>
			<?php endif; ?>
			</form>
			<?php endif; ?>
			<div class="clear"></div>
		</section>
	</article>
</main>
