<div class="start_page">
	<a href='<?=BASE_URL."/admincontrol"?>'>главная</a>
</div>
<div class="out">
	<a href='<?=BASE_URL."/admin/out"?>'>выход</a>
	<div class="clear"></div>
</div>
<form  action='<?=BASE_URL."/admincontrol/index/search/"?>' method="get">
	<div class="search">
		<div class="exampleSearch">Например, <span class="exampleClick">менеджер по продажам</span></div>
		<div class="extendedSearch"><a href="<?=BASE_URL.'/admincontrol/advanced' ?>">Расширенный поиск</a></div>
		<div class="clear">
			<input type="search" name="search" value="<?=$this->data['data']['search']?>" placeholder="введите текст для поиска">
			<input type="submit" value="найти">
		</div>
		<div class="clear"></div>
	</div>
</form>
