<div class="widget admin">
	<p class='<?php if($this->data['data']['active_all_resume']) echo 'active'?>'>
		<a href='<?=BASE_URL."/admincontrol"?>'>всего анкет:
			<span><?=$this->data['data']['users_count']?></span>
		</a>
	</p>
	<p class='<?php if($this->data['data']['active_all_no_view']) echo 'active'?>'>
		<a href="<?=BASE_URL."/admincontrol/unreviewed/view/no"?>">новые анкеты:
			<span><?=$this->data['data']['count_view_admin_resume']?></span></a></p>
	<p class='<?php if($this->data['data']['folder']) echo 'active'?>' ><a  href="<?=BASE_URL."/admincontrol/folders"?>">отобранные</a></p>
	<?php if($this->data['data']['admin'] === 'main'):?>
		<p class='<?php if($this->data['data']['active_manager']) echo 'active'?>' ><a  href="<?=BASE_URL."/admincontrol/managers"?>">менеджеры</a></p>
	<?php endif; ?>
</div>