<?php //echo "<pre>";
//print_r($this->data) ?>
<main class="personal education">
<article>
<div class="arrow-right"></div>
<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме без сохранения</a>
<div class="clear"></div>
<section>
<h1>Образование</h1>
<div class="form">
<form action='<?=BASE_URL.'/side/education'?>' id="education" method="post" novalidate="novalidate">
<table>
	<tbody>
	<tr>
		<td><label for="level">Уровень</label></td>
		<td>
			<select class="level" id="level" name="level">
				<option value="Высшее" <?php if($this->data['data']['inputs']['level']['value']==='Высшее')echo"selected"?>>Высшее</option>
				<option value="Бакалавр"<?php if($this->data['data']['inputs']['level']['value']==='Бакалавр')echo"selected"?>>&nbsp;&nbsp;&nbsp;Бакалавр</option>
				<option value="Магистар"<?php if($this->data['data']['inputs']['level']['value']==='Магистар')echo"selected"?>>&nbsp;&nbsp;&nbsp;Магистар</option>
				<option value="Кандидат наук"<?php if($this->data['data']['inputs']['level']['value']==='Кандидат наук')echo"selected"?>>&nbsp;&nbsp;&nbsp;Кандидат наук</option>
				<option value="Доктор наук"<?php if($this->data['data']['inputs']['level']['value']==='Доктор наук')echo"selected"?>>&nbsp;&nbsp;&nbsp;Доктор наук</option>
				<option value="Неоконченное высшее"<?php if ($this->data['data']['inputs']['level']['value']==='Неоконченное высшее')echo"selected"?>>Неоконченное высшее</option>
				<option value="Среднее специальное"<?php if ($this->data['data']['inputs']['level']['value']==='Среднее специальное')echo"selected"?>>Среднее специальное</option>
				<option value="Среднее"<?php if($this->data['data']['inputs']['level']['value']==='Среднее')echo"selected"?>>Среднее</option>
			</select>
			<div class="message"><?=$this->data['data']['inputs']['level']['val']['message']?></div>
		</td>
	</tr>
	<tr>
		<th colspan="2">Основное образование</th>
	</tr>
	</tbody>
</table>
<?php for( $i=0; $i <= $this->data['data']['table_base_education_count']-1; ++$i): ?>
	<?php if($i>=1): ?>
		<div class="delete education base" data-table-base-education-id='<?=$i?>'><img src='<?=BASE_URL ."/public/img/delete.png"?>'>Удалить</div>
	<?php endif; ?>
	<table class="base_education" data-table-base-education-id='<?=$i?>'>
		<tbody>
		<tr>
			<td><label for="names_institutions">Название учебного заведения<span class="required">*</span></label></td>
			<td>
				<input type="text" id="names_institutions" name="names_institutions[<?=$i?>]" value='<?=$this->data['data']['inputs']['names_institutions']['value'][$i]?>'>
				<div class="message"><?=$this->data['data']['inputs']['names_institutions']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="faculties">Факультет<span class="required">*</span></label></td>
			<td>
				<input type="text"  id="faculties"  name="faculties[<?=$i?>]" value='<?=$this->data['data']['inputs']['faculties']['value'][$i]?>'>
				<div class="message"><?=$this->data['data']['inputs']['faculties']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="specialty_specialty">Cпециализация / специальность<span class="required">*</span></label></td>
			<td>
				<input type="text"  id="specialty_specialty"  name="specialties_specialties[<?=$i?>]" value='<?=$this->data['data']['inputs']['specialties_specialties']['value'][$i]?>'>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"><?=$this->data['data']['inputs']['specialties_specialties']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="year_graduation">Год окончания<span class="required">*</span></label></td>
			<td>
				<select name="years_graduations[<?=$i?>]">
					<option value="0"></option>
					<?php for($year = date("Y")+10 ; $year >= 1950; --$year): ?>
						<option value="<?=$year?>" <?php if($this->data['data']['inputs']['years_graduations']['value'][$i]==$year)echo'selected' ?>><?=$year?></option>
					<?php endfor; ?>
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"><?=$this->data['data']['inputs']['years_graduations']['val'][$i]['message']?></div>
			</td>
		</tr>
		</tbody>
	</table>
<?php endfor; ?>
<div class="add_education"><img src='<?=BASE_URL."/public/img/add.png"?>' alt="">Указать еще одно место обучения</div>

<?php for( $i=0; $i <= $this->data['data']['table_training_courses_count']-1; ++$i): ?>
	<?php if($i>=1): ?>
		<div class="delete training courses" data-table-training-courses-id='<?=$i?>'><img src='<?=BASE_URL ."/public/img/delete.png"?>'>Удалить</div>
	<?php endif; ?>
	<table class="training_courses" data-table-training-courses-id='<?=$i?>'>
		<thead>
		<tr>
			<th colspan="2">Повышение квалификации, курсы</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label for="courses_name">Название учебного заведения</label></td>
			<td>
				<input type="text" id="courses_name" name="courses_names[<?=$i?>]" value='<?=$this->data['data']['inputs']['courses_names']['value'][$i]?>'>
				<div class="message"><?=$this->data['data']['inputs']['courses_names']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="follow_organizations">Проводившая организация</label></td>
			<td>
				<input type="text"  id="follow_organizations"  name="follow_organizations[<?=$i?>]" value='<?=$this->data['data']['inputs']['follow_organizations']['value'][$i]?>'>
				<div class="message"><?=$this->data['data']['inputs']['follow_organizations']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="courses_specialty">Cпециализация / специальность</label></td>
			<td>
				<input type="text"  id="courses_specialty"  name="courses_specialties[<?=$i?>]" value='<?=$this->data['data']['inputs']['courses_specialties']['value'][$i]?>'>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"><?=$this->data['data']['inputs']['courses_specialties']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="course_year_graduation">Год окончания</label></td>
			<td>
				<select name="course_years_graduations[<?=$i?>]">
					<option value="0"></option>
					<?php for($year = date("Y")+10 ; $year >= 1950; --$year): ?>
						<option value="<?=$year?>" <?php if($this->data['data']['inputs']['course_years_graduations']['value'][$i]==$year)echo'selected' ?>><?=$year?></option>
					<?php endfor; ?>
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"><?=$this->data['data']['inputs']['course_years_graduations']['val'][$i]['message']?></div>
			</td>
		</tr>
		</tbody>
	</table>
<?php endfor; ?>
<div class="add_training_courses"><img src='<?=BASE_URL."/public/img/add.png"?>' alt="">Указать еще одно повышение квалификации или курсы</div>

<?php for( $i=0; $i <= $this->data['data']['table_count_tests_exams']-1; ++$i): ?>
	<?php if($i>=1): ?>
		<div class="delete test_exam" data-table-tests-exams-id='<?=$i?>'><img src='<?=BASE_URL ."/public/img/delete.png"?>'>Удалить</div>
	<?php endif; ?>
	<table class="tests_exams" data-table-tests-exams-id='<?=$i?>'>
		<thead>
		<tr>
			<th colspan="2">Тесты, экзамены</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label for="tests_exams_names">Название</label></td>
			<td>
				<input type="text" id="tests_exams_names" name="tests_exams_names[<?=$i?>]"
				       value='<?=$this->data['data']['inputs']['tests_exams_names']['value'][$i]?>'>
				<div class="message"><?=$this->data['data']['inputs']['tests_exams_names']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="tests_exams_follow_organizations">Проводившая организация</label></td>
			<td>
				<input type="text"  id="tests_exams_follow_organizations"
				       name="tests_exams_follow_organizations[<?=$i?>]" value='<?=$this->data['data']['inputs']['tests_exams_follow_organizations']['value'][$i]?>'>
				<div class="message"><?=$this->data['data']['inputs']['tests_exams_follow_organizations']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="tests_exams_specialty">Cпециализация /
					специальность</label></td>
			<td>
				<input type="text"  id="tests_exams_specialty"  name="tests_exams_specialty[<?=$i?>]" value='<?=$this->data['data']['inputs']['tests_exams_specialty']['value'][$i]?>'>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"><?=$this->data['data']['inputs']['tests_exams_specialty']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="tests_exams_years_graduations">Год сдачи</label></td>
			<td>
				<select name="tests_exams_years_graduations[<?=$i?>]">
					<option value="0"></option>
					<?php for($year = date("Y")+10 ; $year >= 1950; --$year): ?>
						<option value="<?=$year?>" <?php if($this->data['data']['inputs']['tests_exams_years_graduations']['value'][$i]==$year)echo'selected' ?>><?=$year?></option>
					<?php endfor; ?>
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"><?=$this->data['data']['inputs']['tests_exams_years_graduations']['val'][$i]['message']?></div>
			</td>
		</tr>
		</tbody>
	</table>
<?php endfor; ?>
<div class="add_tests_exams"><img src='<?=BASE_URL."/public/img/add.png"?>' alt="">Указать еще
	один тест или экзамен</div>


<?php for( $i=0; $i <= $this->data['data']['table_count_electronic_certificates']-1; ++$i): ?>
	<?php if($i>=1): ?>
		<div class="delete electronic_certificates" data-table-electronic-certificates-id='<?=$i?>'><img src='<?=BASE_URL ."/public/img/delete.png"?>'>Удалить</div>
	<?php endif; ?>
	<table class="electronic_certificates" data-table-electronic-certificates-id='<?=$i?>'>
		<thead>
		<tr>
			<th colspan="2">Электронные сертификаты</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label for="electronic_certificates_names">Название</label></td>
			<td>
				<input type="text" id="electronic_certificates_names" name="electronic_certificates_names[<?=$i?>]" value='<?=$this->data['data']['inputs']['electronic_certificates_names']['value'][$i]?>'>
				<div class="message"><?=$this->data['data']['inputs']['electronic_certificates_names']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="electronic_certificates_years_graduations">Год получения</label></td>
			<td>
				<select name="electronic_certificates_years_graduations[<?=$i?>]">
					<option value="0"></option>
					<?php for($year = date("Y")+10 ; $year >= 1950; --$year): ?>
						<option value="<?=$year?>" <?php if($this->data['data']['inputs']['electronic_certificates_years_graduations']['value'][$i]==$year)echo'selected' ?>><?=$year?></option>
					<?php endfor; ?>
				</select>
				<div class="message"><?=$this->data['data']['inputs']['electronic_certificates_years_graduations']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td><label for="electronic_certificates_links">Ссылка на сертификат</label></td>
			<td>
				<input type="text"  id="electronic_certificates_links" name="electronic_certificates_links[<?=$i?>]" value='<?=$this->data['data']['inputs']['electronic_certificates_links']['value'][$i]?>'>
				<div class="message"><?=$this->data['data']['inputs']['electronic_certificates_links']['val'][$i]['message']?></div>
			</td>
		</tr>
		</tbody>
	</table>
<?php endfor; ?>
<div class="add_electronic_certificates"><img src='<?=BASE_URL."/public/img/add.png"?>' alt="">Указать еще
	сертификат</div>

<table class="possessions_language">
	<thead>
	<tr>
		<th colspan="2">Владения языками</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td><label for="native_language">Родной язык</label></td>
		<td>
			<select id="native_language" name="native_language">
				<?php foreach($this->data['data']['languages'] as  $language): ?>
					<option value="<?=$language?>" <?php if($this->data['data']['inputs']['native_language']['value']===$language)echo'selected'?>><?=$language?></option>
				<?php endforeach; ?>
			</select>
			<div class="message"><?=$this->data['data']['inputs']['native_language']['val']['message']?></div>
		</td>
	</tr>

	<tr>
		<td><label for="language_english">Английский</label></td>
		<td>
			<select id="language_english" name="language_english">
				<option value="Не владею" <?php if ($this->data['data']['inputs']['language_english']['value']==="Не владею")echo'selected'?>>Не владею</option>
				<option value="Базовые знания"<?php if ($this->data['data']['inputs']['language_english']['value']==="Базовые знания")echo'selected'?>>Базовые знания</option>
				<option value="Читаю профессиональную литературу"<?php if ($this->data['data']['inputs']['language_english']['value']==="Читаю профессиональную литературу")echo'selected'?>>Читаю профессиональную литературу</option>
				<option value="Могу проходить интервью"<?php if ($this->data['data']['inputs']['language_english']['value']==="Могу проходить интервью")echo'selected'?>>Могу проходить интервью</option>
				<option value="Свободно владею"<?php if ($this->data['data']['inputs']['language_english']['value']==="Свободно владею")echo'selected'?>>Свободно владею</option>
			</select>
			<div class="message"><?=$this->data['data']['inputs']['language_english']['val']['message']?></div>
		</td>
	</tr>

	<tr>
		<td><label for="language_germany">Немецкий</label></td>
		<td>
			<select id="language_germany" name="language_germany">
				<option value="Не владею" <?php if ($this->data['data']['inputs']['language_germany']['value']==="Не владею")echo'selected'?>>Не владею</option>
				<option value="Базовые знания"<?php if ($this->data['data']['inputs']['language_germany']['value']==="Базовые знания")echo'selected'?>>Базовые знания</option>
				<option value="Читаю профессиональную литературу"<?php if ($this->data['data']['inputs']['language_germany']['value']==="Читаю профессиональную литературу")echo'selected'?>>Читаю профессиональную литературу</option>
				<option value="Могу проходить интервью"<?php if ($this->data['data']['inputs']['language_germany']['value']==="Могу проходить интервью")echo'selected'?>>Могу проходить интервью</option>
				<option value="Свободно владею"<?php if ($this->data['data']['inputs']['language_germany']['value']==="Свободно владею")echo'selected'?>>Свободно владею</option>
			</select>
			<div class="message"><?=$this->data['data']['inputs']['language_germany']['val']['message']?></div>
		</td>
	</tr>
	<tr>
		<td><label for="language_french">Французский</label></td>
		<td>
			<select id="language_french" name="language_french">
				<option value="Не владею" <?php if ($this->data['data']['inputs']['language_french']['value']==="Не владею")echo'selected'?>>Не владею</option>
				<option value="Базовые знания"<?php if ($this->data['data']['inputs']['language_french']['value']==="Базовые знания")echo'selected'?>>Базовые знания</option>
				<option value="Читаю профессиональную литературу"<?php if ($this->data['data']['inputs']['language_french']['value']==="Читаю профессиональную литературу")echo'selected'?>>Читаю профессиональную литературу</option>
				<option value="Могу проходить интервью"<?php if ($this->data['data']['inputs']['language_french']['value']==="Могу проходить интервью")echo'selected'?>>Могу проходить интервью</option>
				<option value="Свободно владею"<?php if ($this->data['data']['inputs']['language_french']['value']==="Свободно владею")echo'selected'?>>Свободно владею</option>
			</select>
			<div class="message"><?=$this->data['data']['inputs']['language_french']['val']['message']?></div>
		</td>
	</tr>
	<?php if($this->data['data']['inputs']['language_further']['value'][0]): ?>
		<?php for( $i=0; $i < $this->data['data']['tr_count_language']; ++$i): ?>
			<tr data-tr-language-further-id='<?=$i?>'>
				<td  colspan="2" class="delete language" data-tr-language-further-id='<?=$i?>'><img src='<?=BASE_URL ."/public/img/delete.png"?>'>Удалить</td>
			</tr>
			<tr data-tr-language-further-id='<?=$i?>'>
				<td>
					<select id="language_further" name="language_further[<?=$i?>]">
						<?php foreach($this->data['data']['languages'] as  $language): ?>
							<option value="<?=$language?>" <?php if ($this->data['data']['inputs']['language_further']['value'][$i]===$language)echo'selected'?>><?=$language?></option>
						<?php endforeach; ?>
					</select>
				</td>
				<td>
					<select id="language_further_level" name="language_further_level[<?=$i?>]">
						<option value="Не владею" <?php if ($this->data['data']['inputs']['language_further_level']['value'][$i]==="Не владею")echo'selected'?>>Невладею</option>
						<option value="Базовые знания"<?php if ($this->data['data']['inputs']['language_further_level']['value'][$i]==="Базовые знания")echo'selected'?>>Базовые знания</option>
						<option value="Читаю профессиональную литературу"<?php if ($this->data['data']['inputs']['language_further_level']['value'][$i]==="Читаю профессиональную литературу")echo'selected'?>>Читаю профессиональную литературу</option>
						<option value="Могу проходить интервью"<?php if ($this->data['data']['inputs']['language_further_level']['value'][$i]==="Могу проходить интервью")echo'selected'?>>Могу проходить интервью</option>
						<option value="Свободно владею"<?php if ($this->data['data']['inputs']['language_further_level']['value'][$i]==="Свободно владею")echo'selected'?>>Свободно владею</option>
					</select>
					<div class="message"><?=$this->data['data']['inputs']['language_further_level']['val'][$i]['message']?></div>
				</td>
			</tr>
		<?php endfor; ?>
	<?php endif ?>
	</tbody>
</table>
<div class="add_language"><img src='<?=BASE_URL."/public/img/add.png"?>' alt="">Указать еще один язык</div>
<table>
	<tfoot>
	<tr>
		<td colspan="2">
			<div>
				<input type="submit" id="saveEducation"  name="saveEducation" value="Сохранить">
				<a class="back" href="<?=BASE_URL?>">Отмена</a>
			</div>
		</td>
	</tr>
	</tfoot>
</table>
</form>
</div>
</section>
</article>
</main>