<?php //echo "<pre>";
//print_r($this->data) ?>
<main class="personal education">
	<article>
		<div class="arrow-right"></div>
		<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме без сохранения</a>
		<div class="clear"></div>
		<section>
			<h1>Образование</h1>
			<div class="form">
				<form action='<?=BASE_URL.'/side/education'?>' id="education" method="post" novalidate="novalidate">
					<table>
						<tbody>
						<tr>
							<td><label for="level">Уровень</label></td>
							<td>
								<select class="level" id="level" name="level">
									<option value="Высшее" <?php if($this->data['data']['inputs']['level']['value']==='Высшее')echo"selected"?>>Высшее</option>
									<option value="Бакалавр"<?php if($this->data['data']['inputs']['level']['value']==='Бакалавр')echo"selected"?>>&nbsp;&nbsp;&nbsp;Бакалавр</option>
									<option value="Магистар"<?php if($this->data['data']['inputs']['level']['value']==='Магистар')echo"selected"?>>&nbsp;&nbsp;&nbsp;Магистар</option>
									<option value="Кандидат наук"<?php if($this->data['data']['inputs']['level']['value']==='Кандидат наук')echo"selected"?>>&nbsp;&nbsp;&nbsp;Кандидат наук</option>
									<option value="Доктор наук"<?php if($this->data['data']['inputs']['level']['value']==='Доктор наук')echo"selected"?>>&nbsp;&nbsp;&nbsp;Доктор наук</option>
									<option value="Неоконченное высшее"<?php if ($this->data['data']['inputs']['level']['value']==='Неоконченное высшее')echo"selected"?>>Неоконченное высшее</option>
									<option value="Среднее специальное"<?php if ($this->data['data']['inputs']['level']['value']==='Среднее специальное')echo"selected"?>>Среднее специальное</option>
									<option value="Среднее"<?php if($this->data['data']['inputs']['level']['value']==='Среднее')echo"selected"?>>Среднее</option>
								</select>
								<div class="message"><?=$this->data['data']['inputs']['level']['val']['message']?></div>
							</td>
						</tr>
						<tr>
							<th colspan="2">Основное образование</th>
						</tr>
						</tbody>
					</table>
					<?php for( $i=0; $i <= $this->data['data']['table_base_education_count']-1; ++$i): ?>
						<?php if($i>=1): ?>
							<div class="delete education base" data-table-base-education-id='<?=$i?>'><img src='<?=BASE_URL ."/public/img/delete.png"?>'>Удалить</div>
						<?php endif; ?>
						<table class="base_education" data-table-base-education-id='<?=$i?>'>
							<tbody>
							<tr>
								<td><label for="names_institutions">Название учебного заведения<span class="required">*</span></label></td>
								<td>
									<input type="text" id="names_institutions" name="names_institutions[<?=$i?>]" value='<?=$this->data['data']['inputs']['names_institutions']['value'][$i]?>'>
									<div class="message"><?=$this->data['data']['inputs']['names_institutions']['val'][$i]['message']?></div>
								</td>
							</tr>
							<tr>
								<td><label for="faculties">Факультет<span class="required">*</span></label></td>
								<td>
									<input type="text"  id="faculties"  name="faculties[<?=$i?>]" value='<?=$this->data['data']['inputs']['faculties']['value'][$i]?>'>
									<div class="message"><?=$this->data['data']['inputs']['faculties']['val'][$i]['message']?></div>
								</td>
							</tr>
							<tr>
								<td><label for="specialty_specialty">Cпециализация / специальность<span class="required">*</span></label></td>
								<td>
									<input type="text"  id="specialty_specialty"  name="specialties_specialties[<?=$i?>]" value='<?=$this->data['data']['inputs']['specialties_specialties']['value'][$i]?>'>
									<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
									<div class="message"><?=$this->data['data']['inputs']['specialties_specialties']['val'][$i]['message']?></div>
								</td>
							</tr>
							<tr>
								<td><label for="year_graduation">Год окончания<span class="required">*</span></label></td>
								<td>
									<select name="years_graduations[<?=$i?>]">
										<option value="0"></option>
										<?php for($year = date("Y")+10 ; $year >= 1950; --$year): ?>
											<option value="<?=$year?>" <?php if($this->data['data']['inputs']['years_graduations']['value'][$i]==$year)echo'selected' ?>><?=$year?></option>
										<?php endfor; ?>
									</select>
									<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
									<div class="message"><?=$this->data['data']['inputs']['years_graduations']['val'][$i]['message']?></div>
								</td>
							</tr>
							</tbody>
						</table>
					<?php endfor; ?>
					<div class="add_education"><img src='<?=BASE_URL."/public/img/add.png"?>' alt="">Указать еще одно место обучения</div>

					<?php for( $i=0; $i <= $this->data['data']['table_training_courses_count']-1; ++$i): ?>
						<?php if($i>=1): ?>
							<div class="delete training courses" data-table-training-courses-id='<?=$i?>'><img src='<?=BASE_URL ."/public/img/delete.png"?>'>Удалить</div>
						<?php endif; ?>
						<table class="training_courses" data-table-training-courses-id='<?=$i?>'>
							<thead>
							<tr>
								<th>Повышение квалификации, курсы</th>
							</tr>
							</thead>
							<tbody>
							<tr>
								<td><label for="courses_name">Название учебного заведения</label></td>
								<td>
									<input type="text" id="courses_name" name="courses_names[<?=$i?>]" value='<?=$this->data['data']['inputs']['courses_names']['value'][$i]?>'>
									<div class="message"><?=$this->data['data']['inputs']['courses_names']['val'][$i]['message']?></div>
								</td>
							</tr>
							<tr>
								<td><label for="follow_organizations">Проводившая организация</label></td>
								<td>
									<input type="text"  id="follow_organizations"  name="follow_organizations[<?=$i?>]" value='<?=$this->data['data']['inputs']['follow_organizations']['value'][$i]?>'>
									<div class="message"><?=$this->data['data']['inputs']['follow_organizations']['val'][$i]['message']?></div>
								</td>
							</tr>
							<tr>
								<td><label for="courses_specialty">Cпециализация / специальность</label></td>
								<td>
									<input type="text"  id="courses_specialty"  name="courses_specialties[<?=$i?>]" value='<?=$this->data['data']['inputs']['courses_specialties']['value'][$i]?>'>
									<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
									<div class="message"><?=$this->data['data']['inputs']['courses_specialties']['val'][$i]['message']?></div>
								</td>
							</tr>
							<tr>
								<td><label for="course_year_graduation">Год окончания</label></td>
								<td>
									<select name="course_years_graduations[<?=$i?>]">
										<option value="0"></option>
										<?php for($year = date("Y")+10 ; $year >= 1950; --$year): ?>
											<option value="<?=$year?>" <?php if($this->data['data']['inputs']['course_years_graduations']['value'][$i]==$year)echo'selected' ?>><?=$year?></option>
										<?php endfor; ?>
									</select>
									<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
									<div class="message"><?=$this->data['data']['inputs']['course_years_graduations']['val'][$i]['message']?></div>
								</td>
							</tr>
							</tbody>
						</table>
					<?php endfor; ?>
					<div class="add_training_courses"><img src='<?=BASE_URL."/public/img/add.png"?>' alt="">Указать еще одно повышение квалификации или курсы</div>
					<table>
						<tfoot>
						<tr>
							<td colspan="2">
								<div>
									<input type="submit" id="saveEducation"  name="saveEducation" value="Сохранить">
									<a class="back" href="<?=BASE_URL?>">Отмена</a>
								</div>
							</td>
						</tr>
						</tfoot>
					</table>
				</form>
			</div>
		</section>
	</article>
</main>