<main class="personal experience">
<article>
<div class="arrow-right"></div>
<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме</a>
<div class="clear"></div>
<section>
<h1>Опыт работы</h1>
<div class="form">
<form action='<?=BASE_URL.'/side/experience'?>' id="experience_form" method="post" novalidate="novalidate">
<div id="no_experience" class="block_no_experience">БЕЗ ОПЫТА РАБОТЫ:
	<input type="checkbox" <?php if(!$this->data['data']['inputs']['no_experience']['value']) echo "checked"?> name="no_experience" value="yes" >
</div>
<div id="table_organizations">
	<?php for( $i=0; $i <= $this->data['data']['table_count_work']-1; ++$i): ?>
		<?php if($i>=1): ?>
			<div  class="delete experience" data-table-experience-id='<?=$i?>'><img src='<?=BASE_URL ."/public/img/delete.png"?>'>Удалить</div>
		<?php endif; ?>
		<table  data-table-experience-id='<?=$i?>'>
			<tbody>
			<tr>
				<td><label>Организация<span class="required input">Обязательно для заполнения</span></label></td>
				<td>
					<input type="text"  class="organizations"  name="organizations[<?=$i?>]"
					       value='<?=$this->data['data']['inputs']['organizations']['value'][$i]?>'>
					<div class="message"><?=$this->data['data']['inputs']['organizations']['val'][$i]['message']?></div>
				</td>
			</tr>
			<tr>
				<td><label>Регион<span class="required input">Обязательно для заполнения</span></label></td>
				<td>
					<input class="regions" type="text"  name="regions[<?=$i?>]"
					       value='<?=$this->data['data']['inputs']['regions']['value'][$i]?>'>
					<div class="message"><?=$this->data['data']['inputs']['regions']['val'][$i]['message']?></div>
				</td>
			</tr>
			<tr>
				<td><label>Сайт</label></td>
				<td>
					<input type="text"  name="sites[<?=$i?>]"
					       value='<?=$this->data['data']['inputs']['sites']['value'][$i]?>'>
					<div class="message"><?=$this->data['data']['inputs']['sites']['val']['message'][$i]?></div>
				</td>
			</tr>
			<tr>
				<td><label>Сфера деятельности компании</label></td>
				<td>
					<input type="text" class="field_activities"  name="field_activities[<?=$i?>]"
					       value='<?=$this->data['data']['inputs']['field_activities']['value'][$i]?>'>
					<div class="message"><?=$this->data['data']['inputs']['field_activities']['val'][$i]['message']?></div>
				</td>
			</tr>
			<tr>
				<td><label for="positions">Должность<span class="required input">Обязательно для заполнения</span></label></td>
				<td>
					<input type="text" class="positions"  name="positions[<?=$i?>]"
					       value='<?=$this->data['data']['inputs']['positions']['value'][$i]?>'>
					<div class="message"><?=$this->data['data']['inputs']['positions']['val'][$i]['message']?></div>
				</td>
			</tr>
			<tr>
				<td><label>Начало работы<span class="required input">Обязательно для заполнения</span></label></td>
				<td>
					<select name="getting_starteds[<?=$i?>][month]">
						<?php
						foreach(array(1=>"январь",
							        2=>"февраль",
							        3=>"март",
							        4=>"апрель",
							        5=>"май",
							        6=>"июнь",
							        7=>"июль",
							        8=>"август",
							        9=>"сентябрь",
							        10=>"октябрь",
							        11=>"ноябрь",
							        12=>"декабрь") as $key => $month):?>
							<option value='<?=$key?>' <?php if($this->data['data']['inputs']['getting_starteds']['value'][$i]['month']==$key)echo'selected'?>><?=$month?></option>
						<?php endforeach; ?>
					</select>
					<select name="getting_starteds[<?=$i?>][year]">
						<option value="0"></option>
						<?php for($d=1950, $len=(date('Y')); $d <= $len; ++$d): ?>
							<option value='<?=$d?>'<?php if($this->data['data']['inputs']['getting_starteds']['value'][$i]['year']==$d) echo'selected'?>><?=$d?></option>
						<?php endfor; ?>
					</select>
					<input type="checkbox" name="at_the_moments[<?=$i?>]" <?php if ($this->data['data']['inputs']['at_the_moments']['value'][$i]==='true') echo'checked'?> value="true">По настоящее время
					<div class="message"><?=$this->data['data']['inputs']['getting_starteds']['val'][$i]['message']?></div>
				</td>
			</tr>
			<tr>
				<td><label>Окончание работы<span class="required input">Обязательно для заполнения</span></label></td>
				<td>
					<select name="closing_works[<?=$i?>][month]">
						<?php
						foreach(array(1=>"январь",
							        2=>"февраль",
							        3=>"март",
							        4=>"апрель",
							        5=>"май",
							        6=>"июнь",
							        7=>"июль",
							        8=>"август",
							        9=>"сентябрь",
							        10=>"октябрь",
							        11=>"ноябрь",
							        12=>"декабрь") as $key => $month):?>
							<option value='<?=$key?>' <?php if ($this->data['data']['inputs']['closing_works']['value'][$i]['month']==$key) echo'selected'?>><?=$month?></option>
						<?php endforeach; ?>
					</select>
					<select name="closing_works[<?=$i?>][year]">
						<option value="0"></option>
						<?php for($d=1950, $len=(date('Y'))+50; $d <= $len; ++$d): ?>
							<option value='<?=$d?>' <?php if ($this->data['data']['inputs']['closing_works']['value'][$i]['year']==$d) echo'selected'?>><?=$d?></option>
						<?php endfor; ?>
					</select>
					<div class="message"><?=$this->data['data']['inputs']['closing_works']['val'][$i]['message']?></div>
				</td>
			</tr>
			<tr>
				<td class="functions" ><label for="functions">Обязанности, функции, достижения<span class="required input">Обязательно для заполнения</span></label></td>
				<td class="function_td">
					<textarea name="functions[<?=$i?>]"><?=$this->data['data']['inputs']['functions']['value'][$i]?></textarea>
					<p>Не ограничивайтесь одним-двумя словами, а подробно опишите ваши обязанности и результаты</p>
					<div class="message"><?=$this->data['data']['inputs']['functions']['val'][$i]['message']?></div>
				</td>
			</tr>
			</tbody>
		</table>
	<?php endfor; ?>
	<?php if($this->data['data']['admin'] !== 'manager'): ?>
		<div  class="add_position" ><img src='<?=BASE_URL."/public/img/add.png"?>' alt="">Добавить место работы</div>
	<?php endif; ?>
</div>
<table class="key_skills" id="skill">
	<tbody>
	<tr>
		<td><label for="key_skill">Ключевые навыки<span class="required input">Обязательно для заполнения</span></label></td>
		<td class="skills_td">
			<input type="text" id="key_skill" name="key_skills" value=''>
			<input class="button_skill" type="button" value="добавить">
			<div class="message"><?=$this->data['data']['inputs']['key_skills']['val']['message']?></div>
		</td>
	</tr>
	<tr class="skills_td">
		<td colspan="2">
			<div class="add_skills_hid">
				<?php foreach($this->data['data']['inputs']['key_skills']['value'] as $skills): ?>
					<?php if($skills):?>
						<span><input type='hidden' name='skills_hidden[]' value='<?=$skills?>'><?=$skills?><img class="delete_skills" src="<?=BASE_URL ."/public/img/remove.png"?>"></span>
					<?php endif?>
				<?php endforeach;?>
			</div>
		</td>
	</tr>
	<tr>
		<td>
			<label for="about_s"><b>Обо мне</b></label><br>
			<p id="ab_self" class="about_self">
				Ваше хобби,
				<br>личные качества,
				<br>любая дополнительная<br>информация
			</p>
		</td>
		<td class="about_me" id="ab_self">
			<textarea id="about_s" name="about_self"><?=$this->data['data']['inputs']['about_self']['value']?></textarea>
			<div class="message"><?=$this->data['data']['inputs']['about_self']['val']['message']?></div>
		</td>
	</tr>
	</tbody>
</table>
<?php for( $i=0; $i <= $this->data['data']['table_count_recommendations']-1; ++$i): ?>
	<?php if($i>=1): ?>
		<div class="delete recommendations" data-table-recommendations-id='<?=$i?>'><img src='<?=BASE_URL ."/public/img/delete.png"?>'>Удалить</div>
	<?php endif; ?>
	<table id="reg" data-table-recommendations-id="<?=$i?>" class="recommendations">
		<tbody>
		<tr>
			<td colspan="2">Рекомендации</td>
		</tr>
		<tr>
			<td>Имя</td>
			<td>
				<input type="text" name="recommend_names[<?=$i?>]" value="<?=$this->data['data']['inputs']['recommend_names']['value'][$i]?>">
				<div class="message"><?=$this->data['data']['inputs']['recommend_names']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td>Должность</td>
			<td>
				<input class="positions" type="text" name="recommend_position[<?=$i?>]"
				       value="<?=$this->data['data']['inputs']['recommend_position']['value'][$i]?>">
				<div class="message"><?=$this->data['data']['inputs']['recommend_position']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td>Организация</td>
			<td>
				<input class="organizations" type="text" name="recommend_organization[<?=$i?>]"
				       value="<?=$this->data['data']['inputs']['recommend_organization']['value'][$i]?>">
				<div class="message"><?=$this->data['data']['inputs']['recommend_organization']['val'][$i]['message']?></div>
			</td>
		</tr>
		<tr>
			<td>Телефон</td>
			<td>
				<input type="text" name="recommend_phone[<?=$i?>]" value="<?=$this->data['data']['inputs']['recommend_phone']['value'][$i]?>">
				<div class="message"><?=$this->data['data']['inputs']['recommend_phone']['val'][$i]['message']?></div>
			</td>
		</tr>
		</tbody>
	</table>
<?php endfor; ?>
<?php if($this->data['data']['admin'] !== 'manager'): ?>
	<div class="add_recommendations"><img src='<?=BASE_URL."/public/img/add.png"?>' alt="">Добавить рекомендацию</div>
<?php endif; ?>
<table class="foot_table">
	<tfoot>
	<?php if($this->data['data']['admin'] !== 'manager'): ?>
		<tr>
			<td colspan="2">
				<div>
					<input type="submit" id="submitExperience"  name="saveExperience" value="Сохранить">
					<a class="back" href="<?=BASE_URL?>">Отмена</a>
				</div>
			</td>
		</tr>
	<?php endif; ?>
	</tfoot>
</table>
</form>
</div>
</section>
</article>
</main>