<?php //echo "<pre>";
//print_r($this->data['data']['inputs']['currency']['value'])?>
<main class="personal position">
	<article>
		<div class="arrow-right"></div>
		<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме без сохранения</a>
		<div class="clear"></div>
		<section>
			<h1>Желаемая должность и зарплата</h1>
			<div class="form">
				<form  action='<?=BASE_URL.'/side/position'?>' id="position" method="post" novalidate="novalidate">
					<table>
						<tbody>
						<tr>
							<td><label for="desired_position">Желаемая должность</label></td>
							<td>
								<input type="text"  id="desired_position"  name="desired_position" value='<?=$this->data['data']['inputs']['desired_position']['value']?>'>
								<div class="message"><?=$this->data['data']['inputs']['desired_position']['val']['message']?></div>
							</td>
						</tr>
						<tr>
							<td><label for="professional_area">Профессиональная область</label></td>
							<td>
								<input type="text"  id="professional_area"  name="professional_area" value='<?=$this->data['data']['inputs']['professional_area']['value']?>'>
								<div class="message"><?=$this->data['data']['inputs']['professional_area']['val']['message']?></div>
							</td>
						</tr>
						<tr>
							<td><label for="salary">Зарплата</label></td>
							<td>
								<input type="text"  id="salary"  name="salary" value='<?=$this->data['data']['inputs']['salary']['value']?>'>
								<select id="currency" name="currency">
									<option value="бел. руб."<?php if('бел. руб.'===$this->data['data']['inputs']['currency']['value'])echo'selected'?>>бел. руб.</option>
									<option value="рос. руб."<?php if('рос. руб.'===$this->data['data']['inputs']['currency']['value'])echo'selected'?>>рос. руб.</option>
									<option value="EUR"<?php if('EUR'===$this->data['data']['inputs']['currency']['value'])echo'selected'?>>EUR</option>
									<option value="USD"<?php if('USD'===$this->data['data']['inputs']['currency']['value'])echo'selected'?>>USD</option>
								</select>
								<div class="message"><?=$this->data['data']['inputs']['salary']['val']['message']?></div>
							</td>
						</tr>
						<tr>
							<td><label for="employment">Занятость</label></td>
							<td>
								<div class="container">
									<input type="checkbox" name='employment[]'<?php if(in_array('Полная занятость',$this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Полная занятость">Полная занятость<br>
									<input type="checkbox" name='employment[]'<?php if(in_array('Частичная занятость',$this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Частичная занятость">Частичная занятость <br>
									<input type="checkbox" name='employment[]'<?php if(in_array('Проектная/Временная работа',$this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Проектная/Временная работа">Проектная/Временная работа <br>
									<input type="checkbox" name='employment[]'<?php if(in_array('Волонтерство' , $this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Волонтерство">Волонтерство <br>
									<input type="checkbox" name='employment[]'<?php if(in_array('Стажировка',$this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Стажировка">Стажировка
								</div>
								<div class="message"><?=$this->data['data']['inputs']['employment']['val']['message']?></div>
							</td>
						</tr>
						<tr>
							<td><label for="schedule">График работы</label></td>
							<td>
								<div class="container">
									<input type="checkbox" name='schedule[]'<?php if(in_array('Полный день',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Полный день">Полный день<br>
									<input type="checkbox" name='schedule[]'<?php if(in_array('Сменный график',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Сменный график">Сменный график<br>
									<input type="checkbox" name='schedule[]'<?php if(in_array('Гибкий график',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Гибкий график">Гибкий график<br>
									<input type="checkbox" name='schedule[]'<?php if(in_array('Удаленная работа',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Удаленная работа">Удаленная работа<br>
									<input type="checkbox" name='schedule[]'<?php if(in_array('Вахтовый метод',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Вахтовый метод">Вахтовый метод
								</div>
								<div class="message"><?=$this->data['data']['inputs']['schedule']['val']['message']?></div>
							</td>
						</tr>
						</tbody>
						<tfoot>
						<tr>
							<td colspan="2">
								<div>
									<input type="submit" id="submitPosition"  name="savePosition" value="Сохранить">
									<a class="back" href="<?=BASE_URL?>">Отмена</a>
								</div>
							</td>
						</tr>
						</tfoot>
					</table>
				</form>
			</div>
		</section>
	</article>
</main>