<main class="personal position">
	<article>
		<div class="arrow-right"></div>
		<a class='no-save' href="<?=BASE_URL?>">Вернуться к резюме</a>
		<div class="clear"></div>
		<section>
			<h1>Желаемая должность и зарплата</h1>
			<div class="form">
				<form  action='<?=BASE_URL.'/side/position'?>' id="position_form" method="post">
					<table>
						<tbody>
						<tr>
							<td>
								<label for="desired_position">Желаемая должность<span class="required input">Обязательно для заполнения</span></label>
							</td>
							<td>
								<input type="text"  id="desired_position"  name="desired_position" value='<?=htmlspecialchars($this->data['data']['inputs']['desired_position']['value'],ENT_QUOTES)?>'>
								<div class="message"><?=$this->data['data']['inputs']['desired_position']['val']['message']?></div>
							</td>
						</tr>
						<tr>
							<td>
								<label for="professional_area">Профессиональная область<span class="required input">Обязательно для заполнения</span></label>
							</td>
							<td>

								<div id="professionalAreaBlock">
									<?php if(!empty($this->data['data']['inputs']['professional_area']['value']['title'])): ?>
										<p  data-professional-area-id="{{id}}"><?=$this->data['data']['inputs']['professional_area']['value']['title']?><span class="closeBlock"></span></p>
										<ul>
											<input type="hidden" name='professional_area[title]' value='<?=$this->data['data']['inputs']['professional_area']['value']['title']?>'>
											<?php foreach($this->data['data']['inputs']['professional_area']['value']['children'] as $value): ?>
												<li data-professional-area-children-id ={{this.id}}>
													<input type="hidden" name='professional_area[children][]' value='<?=$value?>'><?=$value?><span class="closeBlock"></span>
												</li>
											<?php endforeach; ?>
										</ul>
									<?php endif; ?>
								</div>
								<span id="profArea">Указать профобласти</span>

								<div id="wrapperProfessArea">
									<div id="blockBlack"></div>

									<div id="blockArea">
										<div class="wrapperHeader">
											<p>Выбор сфер деятельности</p>
											<p><input type="search" id="text-search"  placeholder="Быстрый поиск" ></p>
											<p>Выбор сфер деятельности</p>
										</div>

										<div id="listProfessArea">
											<ul></ul>
										</div>

										<div class="wrapperFooter">
											<h1 id="enter">Выбрать</h1>
											<h1 id="cancel">Отменить</h1>
										</div>
										<div id="closeGif"></div>
									</div>
								</div>
								<div class="message"><?=$this->data['data']['inputs']['professional_area']['val']['message']?></div>
							</td>
						</tr>
						<tr>
							<td><label for="salary">Зарплата</label></td>
							<td>
								<input type="text"  id="salary"  name="salary" value='<?=$this->data['data']['inputs']['salary']['value']?>'>
								<select id="currency" name="currency">
									<option value="бел. руб."<?php if('бел. руб.'===$this->data['data']['inputs']['currency']['value'])echo'selected'?>>бел. руб.</option>
									<option value="рос. руб."<?php if('рос. руб.'===$this->data['data']['inputs']['currency']['value'])echo'selected'?>>рос. руб.</option>
									<option value="EUR"<?php if('EUR'===$this->data['data']['inputs']['currency']['value'])echo'selected'?>>EUR</option>
									<option value="USD"<?php if('USD'===$this->data['data']['inputs']['currency']['value'])echo'selected'?>>USD</option>
								</select>
								<div class="message"><?=$this->data['data']['inputs']['salary']['val']['message']?></div>
							</td>
						</tr>
						<tr>
							<td>
								<label for="employment">Занятость<span class="required input">Обязательно для заполнения</span></label>
							</td>
							<td>
								<div class="container">
									<input type="checkbox" name='employment[]'<?php if(in_array('Полная занятость',$this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Полная занятость">Полная занятость<br>
									<input type="checkbox" name='employment[]'<?php if(in_array('Частичная занятость',$this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Частичная занятость">Частичная занятость <br>
									<input type="checkbox" name='employment[]'<?php if(in_array('Проектная/Временная работа',$this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Проектная/Временная работа">Проектная/Временная работа <br>
									<input type="checkbox" name='employment[]'<?php if(in_array('Волонтерство' , $this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Волонтерство">Волонтерство <br>
									<input type="checkbox" name='employment[]'<?php if(in_array('Стажировка',$this->data['data']['inputs']['employment']['value']))echo'checked'?> value="Стажировка">Стажировка
								</div>
								<div class="message"><?=$this->data['data']['inputs']['employment']['val']['message']?></div>
							</td>
						</tr>
						<tr>
							<td>
								<label for="schedule">График работы<span class="required input">Обязательно для заполнения</span></label>
							</td>
							<td>
								<div class="container">
									<input type="checkbox" name='schedule[]'<?php if(in_array('Полный день',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Полный день">Полный день<br>
									<input type="checkbox" name='schedule[]'<?php if(in_array('Сменный график',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Сменный график">Сменный график<br>
									<input type="checkbox" name='schedule[]'<?php if(in_array('Гибкий график',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Гибкий график">Гибкий график<br>
									<input type="checkbox" name='schedule[]'<?php if(in_array('Удаленная работа',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Удаленная работа">Удаленная работа<br>
									<input type="checkbox" name='schedule[]'<?php if(in_array('Вахтовый метод',$this->data['data']['inputs']['schedule']['value']))echo'checked'?> value="Вахтовый метод">Вахтовый метод
								</div>
								<div class="message"><?=$this->data['data']['inputs']['schedule']['val']['message']?></div>
							</td>
						</tr>
						</tbody>
						<tfoot>
						<?php if($this->data['data']['admin'] !== 'manager'): ?>
							<tr>
								<td colspan="2">
									<div>
										<input type="submit" id="submitPosition"  name="savePosition" value="Сохранить">
										<a class="back" href="<?=BASE_URL?>">Отмена</a>
									</div>
								</td>
							</tr>
						<?php endif ?>
						</tfoot>
					</table>
				</form>
			</div>
		</section>
	</article>
</main>