<div class="print_content">
	<main class="resume">
		<div class="checkbox_print">
			<?php if(count($this->data['data']['comments'])): ?>
				<p><input id="without_comments" type="checkbox" value="">Без комментариев</p>
			<?php endif ?>
			<?php if(!empty($this->data['data']['conclusion'])): ?>
				<p><input id="without_conclusion" type="checkbox" value="">Без заключения</p>
			<?php endif ?>
			<p><button id="button">Распечатать</button></p>
			<p><a class="back" href="<?=BASE_URL.'/index'?>">вернуться назад</a></p>
		</div>
		<section class="photo_personal_contacts">
			<div class="right">
				<figure>
					<p><img src="<?=BASE_URL.'/files/photo/'.$this->data['data']['photo']?>" alt="" ></p>
				</figure>
			</div>
			<div class="left">
				<div class="personal_data">
					<header>
						<h2><?=$this->data['data']['name']?></h2>
					</header>
					<section>
						<p><?=$this->data['data']['birth_sex_city_move_trip']?></p>
						<p><?=$this->data['data']['auto']?></p>
					</section>
				</div>
				<div class="contacts_data">
					<section>
						<?=$this->data['data']['call_me']?>
					</section>
				</div>
			</div>
		</section>
		<div class="clear"></div>
		<div class="salary_position">
			<header>
				<h1>Желаемая должность и зарплата</h1>
			</header>
			<p><strong><?=$this->data['data']['desired_position']?></strong></p>
			<p><strong><?=$this->data['data']['salary']?></strong></p>
			<p><?=$this->data['data']['professional_area']?></p>
			<p><?=$this->data['data']['employment']?></p>
			<p><?=$this->data['data']['schedule']?></p>
		</div>

		<div class="education_language">
			<section>
				<h1>Образование</h1>
				<?=$this->data['data']['institutions']?>
				<div class="languages">
					<h2>Знание языков</h2>
					<?=$this->data['data']['languages']?>
				</div>
				<?php if($this->data['data']['courses_names']): ?>
					<div class="courses">
						<h4>Повышение квалификации, курсы</h4>
						<?=$this->data['data']['courses_names']?>
					</div>
				<?php endif; ?>
				<?php if($this->data['data']['tests_exams_names']): ?>
					<div class="courses">
						<h4>Тесты, экзамены</h4>
						<?=$this->data['data']['tests_exams_names']?>
					</div>
				<?php endif; ?>
				<?php if($this->data['data']['electronic_certificates_names']): ?>
					<div class="courses">
						<h4>Электронные сертификаты</h4>
						<?=$this->data['data']['electronic_certificates_names']?>
					</div>
				<?php endif; ?>
			</section>
		</div>
		<div class="experience">
			<section>
				<h1>Опыт работы (<?=$this->data['data']['sum_experience']?>)</h1>
				<?=$this->data['data']['experience_organizations']?>
				<div class="skills">
					<h2>Ключевые навыки</h2>
					<p>
						<?=$this->data['data']['experience_key_skills']?>
					</p>
				</div>
				<div class="left_40">
					<h2>Обо мне</h2>
					<p>
						<?=$this->data['data']['experience_about_self']?>
					</p>
				</div>

				<div class="right_60">
					<h2>Рекомендации</h2>
					<?=$this->data['data']['experience_recommend']?>
				</div>
				<div class="clear"></div>
			</section>
		</div>
		<?php if($this->data['data']['name']): ?>
			<div class="nationality_workpermit">
				<header>
					<h1>Гражданство, время в пути до работы</h1>
				</header>
				<?=$this->data['data']['nationality_work_permit']?>
			</div>
		<?php endif; ?>
		<div id="conclusion">
			<?php if(!empty($this->data['data']['conclusion'])): ?>
				<h6>Заключение:</h6>
				<p><?=$this->data['data']['conclusion']?></p>
			<?php endif;?>
		</div>
		<div id="comments">
			<?php if(count($this->data['data']['comments'])): ?>
				<h6>Коментарии:</h6>
				<?php foreach($this->data['data']['comments'] as $value): ?>
					<p class="text_comment"><?=$value['comment']?></p>
					<p><?=$value['name']?> <?=$value['date']?></p>
				<?php endforeach; ?>
			<?php endif;?>
		</div>
	</main>
</div>