<main class="resume" style="font-size: 0.4em">
	<section class="photo_personal_contacts">
		<div class="right">
				<figure >
					<p><a href="<?=BASE_URL.'/profile/photo'?>"><img  src="<?=BASE_URL .'/files/photo/' .$this->data['data']['photo']?>" alt="" ></a></p>
				</figure>
		</div>
		<div class="left">
				<div class="personal_data">
					<header>
						<h2><?=$this->data['data']['name']?></h2>
					</header>
					<section>
						<p><?=$this->data['data']['birth_sex_city_move_trip']?></p>
					</section>
				</div>
			<div class="contacts_data">
				<section>
					<?=$this->data['data']['call_me']?>
				</section>
			</div>
		</div>
	</section>
	<div class="clear"></div>
	<div class="salary_position">
		<header>
			<h1>Желаемая должность и зарплата</h1>
			<h2><?=$this->data['data']['desired_position']?></h2>
			<h3><?=$this->data['data']['salary']?></h3>
		</header>
		<p><?=$this->data['data']['professional_area']?></p>
		<p><?=$this->data['data']['employment']?></p>
		<p><?=$this->data['data']['schedule']?></p>
	</div>

	<div class="education_language">
		<section>
			<h1>Образование</h1>
			<?=$this->data['data']['institutions']?>
			<div class="languages">
				<h4>Знание языков</h4>
				<?=$this->data['data']['languages']?>
			</div>
			<?php if($this->data['data']['courses_names']): ?>
				<div class="courses">
					<h4>Повышение квалификации, курсы</h4>
					<?=$this->data['data']['courses_names']?>
				</div>
			<?php endif; ?>
			<?php if($this->data['data']['tests_exams_names']): ?>
				<div class="courses">
					<h4>Тесты, экзамены</h4>
					<?=$this->data['data']['tests_exams_names']?>
				</div>
			<?php endif; ?>
			<?php if($this->data['data']['electronic_certificates_names']): ?>
				<div class="courses">
					<h4>Электронные сертификаты</h4>
					<?=$this->data['data']['electronic_certificates_names']?>
				</div>
			<?php endif; ?>
		</section>
	</div>
	<div class="experience">
		<section>
			<h1>Опыт работы (<?=$this->data['data']['sum_experience']?>)</h1>
			<?=$this->data['data']['experience_organizations']?>
			<div class="skills">
				<h2>Ключевые навыки</h2>
				<p>
					<?=$this->data['data']['experience_key_skills']?>
				</p>
			</div>
			<div class="left_40">
				<h2>Обо мне</h2>
				<p>
					<?=$this->data['data']['experience_about_self']?>
				</p>
			</div>
			<div class="right_60">
				<h2>Рекомендации</h2>
				<?=$this->data['data']['experience_recommend']?>
			</div>
			<div class="clear"></div>
		</section>
	</div>
	<div class="nationality_workpermit">
		<header>
			<h1>Гражданство, время в пути до работы</h1>
		</header>
		<?=$this->data['data']['nationality_work_permit']?>
	</div>
</main>