<!doctype html>
<head>
	<meta charset="utf-8">
	<title>proconsult</title>
	<link rel="stylesheet" href="<?=BASE_URL?>/public/css/style.css">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
	<!--скрипт для старых браузеров IE-->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
<div class="wrapper">
	<div class="helpers"><?=$this->_helpers_menu?></div>
	<div class="content"><?=$this->_content?></div>
</div>
</body>
<script type="text/javascript">var BASE_URL= '<?=BASE_URL?>'</script>
<?=$this->_javascript?>
<script id="table-template-experience" type="text/x-handlebars-template">
	<div class="delete experience" data-table-experience-id="{{i}}">
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table data-table-experience-id="{{i}}">
		<tbody>
		<tr>
			<td><label>Организация<span class="required">*</span></label></td>
			<td>
				<input class="organizations" type="text"  name="organizations[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Регион<span class="required">*</span></label></td>
			<td>
				<input class="regions" type="text"  name="regions[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Сайт</label></td>
			<td>
				<input type="text"   name="sites[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Сфера деятельности компании</label></td>
			<td>
				<input class="field_activities" type="text"  name="field_activities[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Должность<span class="required">*</span></label></td>
			<td>
				<input class="positions" type="text" name="positions[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Начало работы<span class="required">*</span></label></td>
			<td>
				<select name="getting_starteds[{{i}}][month]">
					{{#month 12}}
					{{this}}
					{{/month}}
				</select>
				<select name="getting_starteds[{{i}}][year]">
					{{#year_start 1950}}
					{{this}}
					{{/year_start}}
				</select>
				<input type="checkbox" name="at_the_moments[{{i}}]" value="true">Понастоящее время
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Окончание работы</label></td>
			<td>
				<select name="closing_works[{{i}}][month]">
					{{#month 12}}
					{{this}}
					{{/month}}
				</select>
				<select name="closing_works[{{i}}][year]">
					{{#year_finish 1950}}
					{{this}}
					{{/year_finish}}
				</select>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td class="functions" ><label>Обязанности, функции, достижения<span class="required">*</span></label></td>
			<td class="function_td">
				<textarea name="functions[{{i}}]"></textarea>
				<p>Не ограничивайтесь одним-двумя словами, а подробно опишите ваши обязанности и результаты</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table-template-recommendations" type="text/x-handlebars-template">
	<div class="delete recommendations" data-table-recommendations-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table data-table-recommendations-id='{{i}}' class="recommendations">
		<tbody>
		<tr>
			<td colspan="2">Рекомендации</td>
		</tr>
		<tr>
			<td>Имя</td>
			<td>
				<input type="text" name="recommend_names[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td>Должность</td>
			<td>
				<input class="positions" type="text" name="recommend_position[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td>Организация</td>
			<td>
				<input class="organizations" type="text" name="recommend_organization[{{i}}]" value="">
				<div class="message"</div>
			</td>
		</tr>
		<tr>
			<td>Телефон</td>
			<td>
				<input type="text" name="recommend_phone[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table-base-education" type="text/x-handlebars-template">
	<hr data-table-base-education-id='{{i}}'>
	<div class="delete education base" data-table-base-education-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="base_education" data-table-base-education-id='{{i}}'>
		<tbody>
		<tr>
			<td><label>Название учебного заведения<span class="required">*</span></label></td>
			<td>
				<input type="text"  name="names_institutions[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Факультет<span class="required">*</span></label></td>
			<td>
				<input type="text"  name="faculties[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Cпециализация / специальность<span class="required">*</span></label></td>
			<td>
				<input type="text" name="specialties_specialties[{{i}}]" value=''>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год окончания<span class="required">*</span></label></td>
			<td>
				<select name="years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table_training_courses" type="text/x-handlebars-template">
	<div class="delete training courses" data-table-training-courses-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="training_courses" data-table-training-courses-id='{{i}}'>
		<thead>
		<tr>
			<th>Повышение квалификации, курсы</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label>Название</label></td>
			<td>
				<input type="text" name="courses_names[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Проводившая организация</label></td>
			<td>
				<input type="text" name="follow_organizations[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Cпециализация / специальность</label></td>
			<td>
				<input type="text" name="courses_specialties[{{i}}]" value=''>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год окончания</label></td>
			<td>
				<select name="course_years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table_tests_exams" type="text/x-handlebars-template">
	<div class="delete test_exam" data-table-tests-exams-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="tests_exams" data-table-tests-exams-id='{{i}}'>
		<thead>
		<tr>
			<th>Тесты, экзамены</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label>Название</label></td>
			<td>
				<input type="text" name="tests_exams_names[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Проводившая организация</label></td>
			<td>
				<input type="text"  name="tests_exams_follow_organizations[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Cпециализация / специальность</label></td>
			<td>
				<input type="text" name="tests_exams_specialty[{{i}}]" value=''>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год сдачи</label></td>
			<td>
				<select name="tests_exams_years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table_electronic_certificates" type="text/x-handlebars-template">
	<div class="delete electronic_certificates" data-table-electronic-certificates-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="electronic_certificates" data-table-electronic-certificates-id='{{i}}'>
		<thead>
		<tr>
			<th>Электронные сертификаты</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label>Название</label></td>
			<td>
				<input type="text" name="electronic_certificates_names[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год получения</label></td>
			<td>
				<select name="electronic_certificates_years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Ссылка на сертификат</label></td>
			<td>
				<input type="text" name="electronic_certificates_links[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="tr_language_further" type="text/x-handlebars-template">
	<tr data-tr-language-further-id='{{i}}'>
		<td  colspan="2" class="delete language" data-tr-language-further-id='{{i}}'><img
				src='{{BASE_URL}}/public/img/delete
		.png'>Удалить</td>
	</tr>
	<tr data-tr-language-further-id='{{i}}'>
		<td>
			<select name="language_further[{{i}}]">
				{{#languages}}
				{{this}}
				{{/languages}}
			</select>
		</td>
		<td>
			<select  name="language_further_level[{{i}}]">
				<option value="Базовые знания" >Базовые знания</option>
				<option value="Читаю профессиональную литературу" >Читаю профессиональную литературу</option>
				<option value="Могу проходить интервью" >Могу проходить интервью</option>
				<option value="Свободно владею" >Свободно владею</option>
			</select>
			<div class="message"></div>
		</td>
	</tr>
</script>

</html>