<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="shortcut icon" href="http://www.proconsult.by/sites/all/themes/pro_consult/favicon.ico" type="image/vnd.microsoft.icon" />
	<meta about="/glavnaya-stranica" property="sioc:num_replies" content="0" datatype="xsd:integer" />
	<meta content="Главная страница" about="/glavnaya-stranica" property="dc:title" />

	<link rel="canonical" href="http://www.proconsult.by/" />
	<link rel="shortlink" href="http://www.proconsult.by/" />
	<title>КОНСАЛТИНГОВЫЙ ЦЕНТР &quot;PRO-CONSULT&quot; | Бизнес-обучение и подбор персонала в РБ и РФ</title>
	<link href="http://allfont.ru/css/?fonts=roboto-condensed-italic" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">

	<link rel="stylesheet" href="<?= BASE_URL.'/public/css/style.min.css' ?>">
	<?= $this->style ?>
	<?= $this->javascriptHeader ?>
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>

<header>
	<div class="header"><?=$this->header?></div>
</header>

<div class="container">
	<div class="wrapper_resume">
		<div class="helpers"><?=$this->helpers_menu?></div>
		<div class="my_content"><?=$this->content?></div>
	</div>
</div>

<footer>
	<div class="footer"><?=$this->footer?></div>
</footer>

</body>
<script id="template-comment" type="text/x-handlebars-template">
	{{#each object}}
	<fieldset>
		<legend>
			{{#equal this.access_delete  "yes"}}
			<span class="closeBlock" title="удалить" data-id-comment = "{{this.id}}"></span>
			<span class="closeBlockEdit" data-id-comment = "{{this.id}}" title="редактировать" data-id-comment="{{this.id}}"></span>
			{{/equal}}
			&nbsp;{{this.name}}&nbsp;{{this.date}}</legend>
		<div class="commentBlockOld">{{this.comment}}</div>
	</fieldset>
	{{/each}}
</script>
<script id="tr-template-mobilePhone" type="text/x-handlebars-template">
	<tr data-mobile-phone="delete">
		<td></td>
		<td>+</td>
		<td><input type="tel"  id="mobile_phone_other"  name="mobile_phone_other" value=''></td>
		<td><input type="radio" name="preferred_communication"  value='5'>Желаемый вид связи</td>
		<td class="message"></td>
	</tr>
	<tr data-mobile-phone="delete">
		<td></td>
		<td></td>
		<td  class="comment" colspan="3">Комментарий<br><input type="text" name="comment_mobile_phone_other" value=''></td>
	</tr>
</script>
<script id="table-template-experience" type="text/x-handlebars-template">
	<hr data-table-experience-id='{{i}}'>
	<div class="delete experience" data-table-experience-id="{{i}}">
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table data-table-experience-id="{{i}}">
		<tbody>
		<tr>
			<td><label>Организация<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input class="organizations" type="text"  name="organizations[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Регион<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input class="regions" type="text"  name="regions[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Сайт</label></td>
			<td>
				<input type="text"   name="sites[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Сфера деятельности компании</label></td>
			<td>
				<input class="field_activities" type="text"  name="field_activities[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Должность<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input class="positions" type="text" name="positions[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Начало работы<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<select name="getting_starteds[{{i}}][month]">
					{{#month 12}}
					{{this}}
					{{/month}}
				</select>
				<select name="getting_starteds[{{i}}][year]">
					{{#year_start 1950}}
					{{this}}
					{{/year_start}}
				</select>
				<input type="checkbox" name="at_the_moments[{{i}}]" value="true">Понастоящее время
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Окончание работы</label></td>
			<td>
				<select name="closing_works[{{i}}][month]">
					{{#month 12}}
					{{this}}
					{{/month}}
				</select>
				<select name="closing_works[{{i}}][year]">
					{{#year_finish 1950}}
					{{this}}
					{{/year_finish}}
				</select>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td class="functions" ><label>Обязанности, функции, достижения<span class="required input">Обязательно для заполнения</span></label></td>
			<td class="function_td">
				<textarea name="functions[{{i}}]"></textarea>
				<p>Не ограничивайтесь одним-двумя словами, а подробно опишите ваши обязанности и результаты</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>
<script id="table-template-recommendations" type="text/x-handlebars-template">
	<hr data-table-recommendations-id='{{i}}'>
	<div class="delete recommendations" data-table-recommendations-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table data-table-recommendations-id='{{i}}' class="recommendations">
		<tbody>
		<tr>
			<td colspan="2">Рекомендации</td>
		</tr>
		<tr>
			<td>Имя</td>
			<td>
				<input type="text" name="recommend_names[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td>Должность</td>
			<td>
				<input class="positions" type="text" name="recommend_position[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td>Организация</td>
			<td>
				<input class="organizations" type="text" name="recommend_organization[{{i}}]" value="">
				<div class="message"</div>
			</td>
		</tr>
		<tr>
			<td>Телефон</td>
			<td>
				<input class="recommend_phone" type="text" name="recommend_phone[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>
<script id="table-base-education" type="text/x-handlebars-template">
	<hr data-table-base-education-id='{{i}}'>
	<div class="delete education base" data-table-base-education-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="base_education" data-table-base-education-id='{{i}}'>
		<tbody>
		<tr>
			<td><label>Название учебного заведения<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input type="text"  name="names_institutions[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Факультет</label></td>
			<td>
				<input type="text"  name="faculties[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Специализация / специальность<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input type="text" name="specialties_specialties[{{i}}]" value=''>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год окончания<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<select name="years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>
<script id="table_training_courses" type="text/x-handlebars-template">
	<hr data-table-training-courses-id='{{i}}'>
	<div class="delete training courses" data-table-training-courses-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="training_courses" data-table-training-courses-id='{{i}}'>
		<thead>
		<tr>
			<th>Повышение квалификации, курсы</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label>Название</label></td>
			<td>
				<input type="text" name="courses_names[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Проводившая организация</label></td>
			<td>
				<input type="text" name="follow_organizations[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Cпециализация / специальность</label></td>
			<td>
				<input type="text" name="courses_specialties[{{i}}]" value=''>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год окончания</label></td>
			<td>
				<select name="course_years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>
<script id="table_tests_exams" type="text/x-handlebars-template">
	<hr data-table-tests-exams-id='{{i}}'>
	<div class="delete test_exam" data-table-tests-exams-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="tests_exams" data-table-tests-exams-id='{{i}}'>
		<thead>
		<tr>
			<th>Тесты, экзамены</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label>Название</label></td>
			<td>
				<input type="text" name="tests_exams_names[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Проводившая организация</label></td>
			<td>
				<input type="text"  name="tests_exams_follow_organizations[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Cпециализация / специальность</label></td>
			<td>
				<input type="text" name="tests_exams_specialty[{{i}}]" value=''>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год сдачи</label></td>
			<td>
				<select name="tests_exams_years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>
<script id="table_electronic_certificates" type="text/x-handlebars-template">
	<hr data-table-electronic-certificates-id='{{i}}'>
	<div class="delete electronic_certificates" data-table-electronic-certificates-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="electronic_certificates" data-table-electronic-certificates-id='{{i}}'>
		<thead>
		<tr>
			<th>Электронные сертификаты</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label>Название</label></td>
			<td>
				<input type="text" name="electronic_certificates_names[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год получения</label></td>
			<td>
				<select name="electronic_certificates_years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Ссылка на сертификат</label></td>
			<td>
				<input type="text" name="electronic_certificates_links[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>
<script id="tr_language_further" type="text/x-handlebars-template">
	<tr data-tr-language-further-id='{{i}}'>
		<td  colspan="2" class="delete language" data-tr-language-further-id='{{i}}'><img src='{{BASE_URL}}/public/img/delete.png'>Удалить</td>
	</tr>
	<tr data-tr-language-further-id='{{i}}'>
		<td>
			<select name="language_further[{{i}}]">
				{{#languages}}
				{{this}}
				{{/languages}}
			</select>
		</td>
		<td>
			<select  name="language_further_level[{{i}}]">
				<option value="базовые знания" >базовые знания</option>
				<option value="читаю профессиональную литературу" >читаю профессиональную литературу</option>
				<option value="могу проходить интервью" >могу проходить интервью</option>
				<option value="свободно владею" >свободно владею</option>
			</select>
			<div class="message"></div>
		</td>
	</tr>
</script>
<script id="contacts_list" type="text/x-handlebars-template">
	<tr>
		<td>
			<label for="{{name}}">{{label}}</label>
		</td>
		<td>
			<img src="{{BASE_URL}}/public/img/{{name}}.png">
		</td>
		<td colspan="3">
			<input type="text" id="{{name}}" name="{{name}}" value=''>
		</td>
	</tr>
</script>

<script type="text/javascript">var BASE_URL= '<?=BASE_URL?>'</script>
<?= $this->javascriptFooter ?>
<script type="text/javascript" src="<?= BASE_URL ?>/public/js/vendor/jquery.scrollUp.min.js"></script>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
	(function (d, w, c) {
		$.scrollUp({
			scrollName: 'scrollUp',
			scrollDistance: 300,
			scrollFrom: 'top',
			scrollSpeed: 300,
			easingType: 'linear',
			animation: 'fade',
			animationSpeed: 200,
			scrollTrigger: false,
			scrollTarget: false,
			scrollText: 'Scroll to top',
			scrollTitle: false,
			scrollImg: true,
			activeOverlay: false,
			zIndex: 2147483647
		});

		(w[c] = w[c] || []).push(function() {
			try {
				w.yaCounter27841548 = new Ya.Metrika({id:27841548,
					webvisor:true,
					clickmap:true,
					accurateTrackBounce:true});
			} catch(e) { }
		});

		var n = d.getElementsByTagName("script")[0],
			s = d.createElement("script"),
			f = function () { n.parentNode.insertBefore(s, n); };
		s.type = "text/javascript";
		s.async = true;
		s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

		if (w.opera == "[object Opera]") {
			d.addEventListener("DOMContentLoaded", f, false);
		} else { f(); }
	})(document, window, "yandex_metrika_callbacks");

</script>
<noscript>
	<div><img src="//mc.yandex.ru/watch/27841548" style="position:absolute; left:-9999px;" alt="" /></div>
</noscript>
<!-- /Yandex.Metrika counter -->
</html>