<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="http://www.proconsult.by/sites/all/themes/pro_consult/favicon.ico" type="image/vnd.microsoft.icon" />
	<meta about="/glavnaya-stranica" property="sioc:num_replies" content="0" datatype="xsd:integer" />
	<meta content="Главная страница" about="/glavnaya-stranica" property="dc:title" />
	<meta name="generator" content="Drupal 7 (http://drupal.org)" />
	<link rel="canonical" href="http://www.proconsult.by/" />
	<link rel="shortlink" href="http://www.proconsult.by/" />
	<title>КОНСАЛТИНГОВЫЙ ЦЕНТР &quot;PRO-CONSULT&quot; | Бизнес-обучение и подбор персонала в РБ и РФ</title>
	<link href="http://allfont.ru/css/?fonts=roboto-condensed-italic" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="<?=BASE_URL?>/public/css/style.css">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
</head>
<body>
<div class="page-wrapper" id="page-wrapper">
	<div class="page" id="page">
		<!-- header -->
		<div class="header-wrapper" id="header">
			<div class="section clearfix">

				<div id="logo-and-slogan" class="logo-and-slogan-wrapper">
					<div class="logo-wrapper site-logo">
						<a href="http://proconsult.by/" title="Главная" rel="home" id="logo">
							<img src="http://proconsult.by/sites/all/themes/pro_consult/logo.png" alt="Главная"/>
						</a>
					</div>
					<div class="slogan-wrapper">
						<div id="site-slogan">
							Бизнес-обучение и подбор персонала в РБ и РФ
						</div>
					</div> <!-- /.slogan-wrapper -->
				</div>
				<div id="header_section" class="h_section section clearfix">
					<div class="region region-header">
						<div id="block-block-4" class="block block-block order-btns-block">
							<div class="content">
								<div class="order-call-btn-wrapper"><a href="http://proconsult.by/node/11?height=500&amp;width=600" class="colorbox-node order-call-btn header-btn">Обратный звонок</a></div>
								<div class="offer-btn-wrapper"><a href="http://proconsult.by/node/12?height=450&amp;width=600" class="colorbox-node offer-btn header-btn">Коммерческое <span>предложение</span></a></div>
							</div>
						</div>
						<div id="block-block-5" class="block block-block header-contacts-block">
							<div class="content">
								<div class="header-adress-wrapper">220017, Республика Беларусь,<br />
									г. Минск, ул. Дунина-Марцинкевича 2/1 оф.206</div>
								<div class="header-phones-wrapper"><span class="header-phone-wrapper">+375 29 <strong>678 32 35</strong></span><span class="header-phone-wrapper">+375 17 <strong>202 21 52</strong></span></div>
								<div class="header-mail-wrapper"><a href="mailto:info@proconsult.by">info@proconsult.by</a></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="main-menu" class="main-menu">
				<div class="section clearfix">
					<div class="region region-main-menu">
						<div id="block-nice-menus-1" class="block block-nice-menus main-menu-block">
							<div class="content">
								<ul class="nice-menu nice-menu-down nice-menu-main-menu nice-menus-processed sf-js-enabled sf-arrows" id="nice-menu-1">
									<li class="menu-224 menu-path-front first odd">
										<a href="http://proconsult.by/"
										   onclick="return confirm('Вы действительно хотите' +
										 ' покинуть страницу!')?true:false" title="" class="active">Вернуться к
											сайту</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div> <!-- /.section, /.main-menu -->
		</div>
	</div>
</div>
<div class="clear"></div>

<div class="wrapper_resume">
	<div class="helpers"><?=$this->_helpers_menu?></div>
	<div class="content"><?=$this->_content?></div>
</div>
<div class="clear"></div>
<div class="footer-wrapper">
	<div class="footer-container">
		<div class="footer-box clearfix">
			<div id="footer" class="footer wrapper-3-row">
				<div class="section clearfix">
					<div class="region region-footer-a">
						<div id="block-block-7" class="block block-block footer-contacts-block clearfix">
							<div class="content">
								<div class="footer-adress-wrapper">220017, Республика Беларусь,<br>
									г. Минск, ул. Дунина-Марцинкевича 2/1 оф.206</div>
								<div class="footer-phones-wrapper"><span class="footer-phone-wrapper">+375 29 <strong>678 32 35</strong></span><span class="footer-phone-wrapper">+375 17 <strong>202 21 52</strong></span></div>
								<div class="footer-mail-wrapper"><a href="mailto:info@proconsult.by">info@proconsult.by</a><br>
									_____________________________________________
									<p>Разработка сайта - <a href="http://ib.by/">ib.by</a></p></div>
							</div>
						</div>
					</div>
					<div class="region region-footer-b">
						<div id="block-block-8" class="block block-block footer-social-block cleafix">
							<h2>Мы в социальных сетях:</h2>
							<div class="content">
								<div>
									<a href="https://twitter.com/ProconsultBy" class="social-link social-link-twitter">Twitter</a><a href="https://www.facebook.com/Proconsult.by?ref=hl&ref_type=bookmark" class="social-link social-link-facebook">Facebook</a><a href="https://vk.com/proconsult" class="social-link social-link-vkontakte">ВКонтакте</a><a href="https://www.youtube.com/channel/UCOfQ7LhG7TDH32txjVNicPg/videos" class="social-link social-link-youtube">Youtube</a>
								</div>
							</div>
						</div>
					</div>
					<div class="region region-footer-c">
						<div id="block-block-15" class="block block-block footer-info-block clearfix">
							<h2>Информация:</h2>
							<div class="content">
								<div class="info-links-wrapper">
									<div class="link-box"><a href="http://www.proconsult.by/statyi" class="info-link" alt="">Статьи</a></div>
									<div class="link-box"><a href="http://www.proconsult.by/vopros-otvet" class="info-link" alt="">Вопрос-ответ</a></div>
									<div class="link-box"><a href="http://www.proconsult.by/publichnaya-oferta" class="info-link" alt="">Публичная оферта</a></div>
									<div class="link-box"><a href="http://www.proconsult.by/trenery" class="info-link" alt="">Тренеры</a></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
<script type="text/javascript">var BASE_URL= '<?=BASE_URL?>'</script>
<?=$this->_javascript?>
<script id="table-template-experience" type="text/x-handlebars-template">
	<hr data-table-experience-id='{{i}}'>
	<div class="delete experience" data-table-experience-id="{{i}}">
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table data-table-experience-id="{{i}}">
		<tbody>
		<tr>
			<td><label>Организация<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input class="organizations" type="text"  name="organizations[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Регион<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input class="regions" type="text"  name="regions[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Сайт</label></td>
			<td>
				<input type="text"   name="sites[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Сфера деятельности компании</label></td>
			<td>
				<input class="field_activities" type="text"  name="field_activities[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Должность<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input class="positions" type="text" name="positions[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Начало работы<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<select name="getting_starteds[{{i}}][month]">
					{{#month 12}}
					{{this}}
					{{/month}}
				</select>
				<select name="getting_starteds[{{i}}][year]">
					{{#year_start 1950}}
					{{this}}
					{{/year_start}}
				</select>
				<input type="checkbox" name="at_the_moments[{{i}}]" value="true">Понастоящее время
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Окончание работы</label></td>
			<td>
				<select name="closing_works[{{i}}][month]">
					{{#month 12}}
					{{this}}
					{{/month}}
				</select>
				<select name="closing_works[{{i}}][year]">
					{{#year_finish 1950}}
					{{this}}
					{{/year_finish}}
				</select>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td class="functions" ><label>Обязанности, функции, достижения<span class="required input">Обязательно для заполнения</span></label></td>
			<td class="function_td">
				<textarea name="functions[{{i}}]"></textarea>
				<p>Не ограничивайтесь одним-двумя словами, а подробно опишите ваши обязанности и результаты</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table-template-recommendations" type="text/x-handlebars-template">
	<hr data-table-recommendations-id='{{i}}'>
	<div class="delete recommendations" data-table-recommendations-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table data-table-recommendations-id='{{i}}' class="recommendations">
		<tbody>
		<tr>
			<td colspan="2">Рекомендации</td>
		</tr>
		<tr>
			<td>Имя</td>
			<td>
				<input type="text" name="recommend_names[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td>Должность</td>
			<td>
				<input class="positions" type="text" name="recommend_position[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td>Организация</td>
			<td>
				<input class="organizations" type="text" name="recommend_organization[{{i}}]" value="">
				<div class="message"</div>
			</td>
		</tr>
		<tr>
			<td>Телефон</td>
			<td>
				<input type="text" name="recommend_phone[{{i}}]" value="">
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table-base-education" type="text/x-handlebars-template">
	<hr data-table-base-education-id='{{i}}'>
	<div class="delete education base" data-table-base-education-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="base_education" data-table-base-education-id='{{i}}'>
		<tbody>
		<tr>
			<td><label>Название учебного заведения<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input type="text"  name="names_institutions[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Факультет<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input type="text"  name="faculties[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Cпециализация / специальность<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<input type="text" name="specialties_specialties[{{i}}]" value=''>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год окончания<span class="required input">Обязательно для заполнения</span></label></td>
			<td>
				<select name="years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table_training_courses" type="text/x-handlebars-template">
	<hr data-table-training-courses-id='{{i}}'>
	<div class="delete training courses" data-table-training-courses-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="training_courses" data-table-training-courses-id='{{i}}'>
		<thead>
		<tr>
			<th>Повышение квалификации, курсы</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label>Название</label></td>
			<td>
				<input type="text" name="courses_names[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Проводившая организация</label></td>
			<td>
				<input type="text" name="follow_organizations[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Cпециализация / специальность</label></td>
			<td>
				<input type="text" name="courses_specialties[{{i}}]" value=''>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год окончания</label></td>
			<td>
				<select name="course_years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table_tests_exams" type="text/x-handlebars-template">
	<hr data-table-tests-exams-id='{{i}}'>
	<div class="delete test_exam" data-table-tests-exams-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="tests_exams" data-table-tests-exams-id='{{i}}'>
		<thead>
		<tr>
			<th>Тесты, экзамены</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label>Название</label></td>
			<td>
				<input type="text" name="tests_exams_names[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Проводившая организация</label></td>
			<td>
				<input type="text"  name="tests_exams_follow_organizations[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Cпециализация / специальность</label></td>
			<td>
				<input type="text" name="tests_exams_specialty[{{i}}]" value=''>
				<p>Например, "Прикладная информатика" или "Управление персоналом"</p>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год сдачи</label></td>
			<td>
				<select name="tests_exams_years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<p>Если учитесь в настоящее время — укажите год предполагаемого окончания</p>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="table_electronic_certificates" type="text/x-handlebars-template">
	<hr data-table-electronic-certificates-id='{{i}}'>
	<div class="delete electronic_certificates" data-table-electronic-certificates-id='{{i}}'>
		<img src='{{BASE_URL}}/public/img/delete.png'>Удалить</div>
	<table class="electronic_certificates" data-table-electronic-certificates-id='{{i}}'>
		<thead>
		<tr>
			<th>Электронные сертификаты</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label>Название</label></td>
			<td>
				<input type="text" name="electronic_certificates_names[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Год получения</label></td>
			<td>
				<select name="electronic_certificates_years_graduations[{{i}}]">
					{{#years}}
					{{this}}
					{{/years}}
				</select>
				<div class="message"></div>
			</td>
		</tr>
		<tr>
			<td><label>Ссылка на сертификат</label></td>
			<td>
				<input type="text" name="electronic_certificates_links[{{i}}]" value=''>
				<div class="message"></div>
			</td>
		</tr>
		</tbody>
	</table>
</script>

<script id="tr_language_further" type="text/x-handlebars-template">
	<tr data-tr-language-further-id='{{i}}'>
		<td  colspan="2" class="delete language" data-tr-language-further-id='{{i}}'><img
				src='{{BASE_URL}}/public/img/delete
		.png'>Удалить</td>
	</tr>
	<tr data-tr-language-further-id='{{i}}'>
		<td>
			<select name="language_further[{{i}}]">
				{{#languages}}
				{{this}}
				{{/languages}}
			</select>
		</td>
		<td>
			<select  name="language_further_level[{{i}}]">
				<option value="базовые знания" >базовые знания</option>
				<option value="читаю профессиональную литературу" >читаю профессиональную литературу</option>
				<option value="могу проходить интервью" >могу проходить интервью</option>
				<option value="свободно владею" >свободно владею</option>
			</select>
			<div class="message"></div>
		</td>
	</tr>
</script>

<script id="contacts_list" type="text/x-handlebars-template">
	<tr>
		<td>
			<label for="{{name}}">{{label}}</label>
		</td>
		<td>
			<img src="{{BASE_URL}}/public/img/{{name}}.png">
		</td>
		<td colspan="3">
			<input type="text" id="{{name}}" name="{{name}}" value=''>
		</td>
	</tr>
</script>



</html>