<main class="admin_control advanced">
<div class="header">
	<?=$this->data['helpers']['header']?>
</div>
<div class="left_admin_control">
	<?=$this->data['helpers']['widget_admin']?>
</div>
<div class="right_admin_control">
<header>
	<h1>Поиск&#160;резюме</h1>
</header>
<form action="<?=BASE_URL.'/admincontrol/advancedresult'?>" class="advancedForm" method="post">
<table>
<tbody>
<tr>
	<td><label for="keywords">Ключевые слова</label></td>
	<td>
		<div class="inputKeywordsBlock">
			<span><input type="text" name="advancedForm[wordKey][input]" id="keywords" value="<?=$this->data['data']['form']['wordKey']['input']?>" title="Ключевые&#160;слова"></span>
			<span><input type="submit" class="prosper-button" name="advancedForm[advancedFormSubmit]" value="Найти"></span>
			<div>
				<span id="targetRadio">
					<span class="resumeSearchSort">Все&#160;слова</span>
					<ul class="radioBlock">
						<li><label><input type="radio" name="advancedForm[wordKey][parse]" <?php if($this->data['data']['form']['wordKey']['parse']==='allWorlds')echo"checked"?> value="allWorlds" checked>Все&#160;слова</label></li>
						<li><label><input type="radio" name="advancedForm[wordKey][parse]" <?php if($this->data['data']['form']['wordKey']['parse']==='someWorlds')echo"checked"?> value="someWorlds">Любое&#160;из&#160;слов</label></li>
						<li><label><input type="radio" name="advancedForm[wordKey][parse]" <?php if($this->data['data']['form']['wordKey']['parse']==='exactWorlds')echo"checked"?> value="exactWorlds">Точная&#160;фраза</label></li>
					</ul>
				</span>
				<span id ="targetCheckbox">
					<span class="resumeSearchSort">везде</span>
					<ul class="checkboxBlock">
						<li><label><input type="checkbox" id="placeSearchAll" name="advancedForm[wordKey][placeSearch][all]"<?php if(isset($this->data['data']['form']['wordKey']['placeSearch']['all']))echo"checked"?>>везде</label></li>
						<li><label><input type="checkbox" name="advancedForm[wordKey][placeSearch][education]"<?php if(isset($this->data['data']['form']['wordKey']['placeSearch']['education']))echo"checked"?>>в&#160;образовании</label></li>
						<li><label><input type="checkbox" name="advancedForm[wordKey][placeSearch][skills]" <?php if(isset($this->data['data']['form']['wordKey']['placeSearch']['skills']))echo"checked"?> >в&#160;ключевых&#160;навыках</label></li>
						<li>
							<label><input type="checkbox" id="workExperience" <?php if(isset($this->data['data']['form']['wordKey']['placeSearch']['experience']))echo"checked"?> name="">в&#160;опыте&#160;работы</label>
							<ul class="childrenUl">
								<li><label><input type="checkbox"<?php if(isset($this->data['data']['form']['wordKey']['placeSearch']['experience']['field_activities']))echo"checked"?> class="work-experience" name="advancedForm[wordKey][placeSearch][experience][field_activities]">в&#160;компаниях&#160;и&#160;отраслях</label></li>
								<li><label><input type="checkbox"<?php if(isset($this->data['data']['form']['wordKey']['placeSearch']['experience']['positions']))echo"checked"?> class="work-experience" name="advancedForm[wordKey][placeSearch][experience][positions]">в&#160;должностях</label></li>
								<li><label><input type="checkbox"<?php if(isset($this->data['data']['form']['wordKey']['placeSearch']['experience']['functions']))echo"checked"?> class="work-experience" name=advancedForm[wordKey][placeSearch][experience][functions]">в&#160;обязанностях</label></li>
							</ul>
						</li>
						<li>
							<span class="buttonCheckboxLi">OK</span>
						</li>
					</ul>
				</span>
			</div>
		</div>
	</td>
</tr>
<tr>
	<td><label for="professional_area">Профессиональная область</label></td>
	<td>
		<span <?php if($this->data['data']['form']['professional_area']) echo"style='display:none'"?> class="professionalAreaLink">Любая<span class="link">Указать профобласти</span></span>
		<div <?php if($this->data['data']['form']['professional_area']) echo"style='display:block'"?> id="inputProfessionalAreaBlock">
			<input type="text" name="advancedForm[professional_area][]" id="professional_area" value="">
			<h1 id="addProfessionalAreaButton" class="prosper-button">Добавить</h1>
			<h1 id="cancelProfessionalAreaButton" class="prosper-button">Отменить</h1>
			<div class="professionalAreaList"><?=$this->data['data']['form']['professional_area']?></div>
		</div>
	</td>
</tr>
<tr>
	<td><label for="city">Регион</label></td>
	<td id="containerCity">
		<input type="text" name="advancedForm[city][]" id="city" value="">
		<h1 id="addCityButton" class="prosper-button">Добавить регион</h1>
		<div class="cityBlock"><?=$this->data['data']['form']['city']?></div>
	</td>
</tr>
<tr>
	<td><label for="salary">Зарплата</label></td>
	<td>
		<span class="salaryInput">
			&#160;от&#160;<input type="text" name="advancedForm[salary][from]" value="<?=$this->data['data']['form']['salary']['from']?>">&#160;до&#160;
			<input class="salaryInput" type="text" name="advancedForm[salary][before]" value="<?=$this->data['data']['form']['salary']['before']?>">
			<select name="advancedForm[salary][currency]">
				<option <?php if($this->data['data']['form']['salary']['currency']==='бел. руб.') echo"selected"?> value="бел. руб.">бел. руб.</option>
				<option <?php if($this->data['data']['form']['salary']['currency']==='рос. руб.') echo"selected"?> value="рос. руб.">рос. руб.</option>
				<option <?php if($this->data['data']['form']['salary']['currency']==='EUR') echo"selected"?> value="EUR">EUR</option>
				<option <?php if($this->data['data']['form']['salary']['currency']==='USD') echo"selected"?> value="USD">USD</option>
			</select>
		</span>
		<span class="salaryInputCheckbox">
			<label><input type="checkbox"  <?php if(isset($this->data['data']['form']['salary']['show_empty']))echo"checked"?> name="advancedForm[salary][show_empty]" value="false">Не&#160;показывать&#160;резюме&#160;без&#160;зарплаты</label>
		</span>
	</td>
</tr>
<tr>
	<td>Требуемый&#160;опыт&#160;работы</td>
	<td>
		<ul class="experience">
			<li><label><input type="checkbox" <?php if(isset($this->data['data']['form']['experience']['no'])) echo"checked"?> name="advancedForm[experience][no]" value="">Нет&#160;опыта</label></li>
			<li><label><input type="checkbox" <?php if(isset($this->data['data']['form']['experience']['one-three'])) echo"checked"?> name="advancedForm[experience][one-three]" value="">От&#160;1&#160;года&#160;до&#160;3&#160;лет</label></li>
			<li><label><input type="checkbox" <?php if(isset($this->data['data']['form']['experience']['three-six'])) echo"checked"?> name="advancedForm[experience][three-six]" value="">От&#160;3&#160;до&#160;6&#160;лет</label></li>
			<li><label><input type="checkbox" <?php if(isset($this->data['data']['form']['experience']['six-more'])) echo"checked"?> name="advancedForm[experience][six-more]" value="">Более&#160;6&#160;лет</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td><label for="education">Образование</label></td>
	<td>
		<select name="advancedForm[education][degree]" id="education">
			<option value="">Не&#160;имеет&#160;значения</option>
			<option value="Высшее" <?php if($this->data['data']['form']['education']['degree']==='Высшее') echo"selected"?>>Высшее</option>
			<option value="Бакалавр" <?php if($this->data['data']['form']['education']['degree']==='Бакалавр') echo"selected"?> >Бакалавр</option>
			<option value="Магистр" <?php if($this->data['data']['form']['education']['degree']==='Магистр') echo"selected"?> >Магистр</option>
			<option value="Кандидат наук" <?php if($this->data['data']['form']['education']['degree']==='Кандидат наук') echo"selected"?> >Кандидат&#160;наук</option>
			<option value="Доктор наук" <?php if($this->data['data']['form']['education']['degree']==='Доктор наук') echo"selected"?> >Доктор&#160;наук</option>
			<option value="Незаконченное высшее" <?php if($this->data['data']['form']['education']['degree']==='Незаконченное высшее') echo"selected"?>  >Незаконченное&#160;высшее</option>
			<option value="Среднее" <?php if($this->data['data']['form']['salary']['education']==='Среднее') echo"selected"?> >Среднее</option>
			<option value="Среднее специальное" <?php if ($this->data['data']['form']['education']['degree']==='Среднее специальное') echo"selected"?> >Среднее&#160;специальное</option>
		</select>
		<div class="names_institutions">
			<span class="link" <?php if(isset($this->data['data']['form']['education']['name']))echo"style='display:none' "?>>Указать названия учебных заведений</span>
			<div class="institutionsBlock" <?php if(isset($this->data['data']['form']['education']['name']))echo"style='display:block' "?>>
				<p>Добавить учебное заведение</p>
				<input type="text" name="advancedForm[education][name]" <?php if(!isset($this->data['data']['form']['education']['name']))echo" disabled "?> value="<?=$this->data['data']['form']['education']['name']?>">
			</div>
		</div>
	</td>
</tr>
<tr>
	<td><label for="nationality">Гражданство</label></td>
	<td>
		<span class="linkSpan" <?php if(isset($this->data['data']['form']['nationality']['name']))echo"style='display:none' "?> >Любая<span class="link">Указать&#160;страну</span></span>
		<div class="hideDiv" <?php if(isset($this->data['data']['form']['nationality']['name']))echo" style='display:block' "?> >
			<p>Добавить&#160;страну</p>
			<input type="text" name="advancedForm[nationality][name]" id="nationality" <?php if(!isset($this->data['data']['form']['nationality']['name']))echo" disabled "?>  value="<?=$this->data['data']['form']['nationality']['name']?>">
		</div>
	</td>
</tr>
<tr>
	<td><label for="work_permit">Разрешение&#160;на&#160;работу</label></td>
	<td>
		<span class="linkSpan" <?php if(isset($this->data['data']['form']['work_permit']['name']))echo"style='display:none' "?>  >Любая<span class="link">Указать&#160;страну</span></span>
		<div class="hideDiv" <?php if(isset($this->data['data']['form']['work_permit']['name']))echo" style='display:block' "?>>
			<p>Добавить&#160;страну</p>
			<input type="text" name="advancedForm[work_permit][name]" id="work_permit" <?php if(!isset($this->data['data']['form']['work_permit']['name']))echo" disabled "?>  value="<?=$this->data['data']['form']['work_permit']['name']?>">
		</div>
	</td>
</tr>
<tr>
	<td><label>Возраст&#160;и&#160;фотография</label></td>
	<td>
		<div class="ageInput">&#160;от&#160;<input type="text" name="advancedForm[age][from]" value="<?=$this->data['data']['form']['age']['from']?>">&#160;до&#160;<input class="salaryInput" type="text" name="advancedForm[age][before]" value="<?=$this->data['data']['form']['age']['before']?>">
		</div>
		<div class="ageInputCheckbox">
			<span><label><input type="checkbox" <?php if(isset($this->data['data']['form']['age']['show_empty']))echo"checked"?>  name="advancedForm[age][show_empty]" value="false">Не&#160;показывать&#160;резюме&#160;без&#160;указания&#160;возраста</label></span>
			<span><label><input type="checkbox" <?php if(isset($this->data['data']['form']['age']['show_photo']))echo"checked"?> name="advancedForm[age][show_photo]" value="false">Только&#160;с&#160;фотографией</label></span>
		</div>
	</td>
</tr>
<tr>
	<td>Пол</td>
	<td>
		<ul class="sex">
			<li><label><input type="radio" name="advancedForm[sex]" <?php if(empty($this->data['data']['form']['sex']))echo"checked"?> value="">Не&#160;имеет&#160;значения</label></li>
			<li><label><input type="radio" name="advancedForm[sex]" <?php if($this->data['data']['form']['sex']==='Мужской')echo"checked"?> value="Мужской">Мужской</label></li>
			<li><label><input type="radio" name="advancedForm[sex]" <?php if($this->data['data']['form']['sex']==='Женский')echo"checked"?> value="Женский">Женский</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td>Тип занятости</td>
	<td>
		<ul class="employment">
			<li><label><input type="checkbox" name="advancedForm[employment][]"<?php if(is_array($this->data['data']['form']['employment'])&&in_array('Полная занятость', $this->data['data']['form']['employment'] ) )echo"checked"?> value="Полная занятость">Полная&#160;занятость</label></li>
			<li><label><input type="checkbox" name="advancedForm[employment][]"<?php if(is_array($this->data['data']['form']['employment'])&&in_array('Частичная занятость', $this->data['data']['form']['employment'] ) )echo"checked"?>  value="Частичная занятость">Частичная&#160;занятость</label></li>
			<li><label><input type="checkbox" name="advancedForm[employment][]"<?php if(is_array($this->data['data']['form']['employment'])&&in_array('Проектная/Временная работа', $this->data['data']['form']['employment'] ) )echo"checked"?>  value="Проектная/Временная работа">Проектная/Временная&#160;работа</label></li>
			<li><label><input type="checkbox" name="advancedForm[employment][]"<?php if(is_array($this->data['data']['form']['employment'])&&in_array('Волонтерство', $this->data['data']['form']['employment'] ) )echo"checked"?>  value="Волонтерство">Волонтерство</label></li>
			<li><label><input type="checkbox" name="advancedForm[employment][]"<?php if(is_array($this->data['data']['form']['employment'])&&in_array('Стажировка', $this->data['data']['form']['employment'] ) )echo"checked"?>  value="Стажировка">Стажировка</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td>График работы</td>
	<td>
		<ul class="schedule">
			<li><label><input type="checkbox" name="advancedForm[schedule][]"<?php if(is_array($this->data['data']['form']['schedule'])&&in_array('Полный день', $this->data['data']['form']['schedule'] ) )echo"checked"?> value="Полный день">Полный&#160;день</label></li>
			<li><label><input type="checkbox" name="advancedForm[schedule][]"<?php if(is_array($this->data['data']['form']['schedule'])&&in_array('Сменныйграфик', $this->data['data']['form']['schedule'] ) )echo"checked"?> value="Сменныйграфик">Сменный&#160;график</label></li>
			<li><label><input type="checkbox" name="advancedForm[schedule][]"<?php if(is_array($this->data['data']['form']['schedule'])&&in_array('Гибкий график', $this->data['data']['form']['schedule'] ) )echo"checked"?> value="Гибкий график">Гибкий&#160;график</label></li>
			<li><label><input type="checkbox" name="advancedForm[schedule][]"<?php if(is_array($this->data['data']['form']['schedule'])&&in_array('Удаленная работа', $this->data['data']['form']['schedule'] ) )echo"checked"?> value="Удаленная работа">Удаленная&#160;работа</label></li>
			<li><label><input type="checkbox" name="advancedForm[schedule][]"<?php if(is_array($this->data['data']['form']['schedule'])&&in_array('Вахтовый метод', $this->data['data']['form']['schedule'] ) )echo"checked"?> value="Вахтовый метод">Вахтовый&#160;метод</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td>Знание языков</td>
	<td>
		<div id="blockLanguage">
			<ul id="languages"></ul>
			<div><span id="linkLanguage">Добавить язык</span></div>
		</div>
	</td>
</tr>
<tr>
	<td>Выводить</td>
	<td>
		<ul class="deduce">
			<li><label><input type="radio" name="advancedForm[deduce][type]"<?php if(!$this->data['data']['form']['deduce']['type'])echo"checked"?> value="0">За&#160;весь&#160;период</label></li>
			<li><label><input type="radio" name="advancedForm[deduce][type]"<?php if($this->data['data']['form']['deduce']['type']==1)echo"checked"?> value="1">За&#160;сутки</label></li>
			<li><label><input type="radio" name="advancedForm[deduce][type]"<?php if($this->data['data']['form']['deduce']['type']==2)echo"checked"?> value="2">За&#160;последние&#160;три&#160;дня</label></li>
			<li><label><input type="radio" name="advancedForm[deduce][type]"<?php if($this->data['data']['form']['deduce']['type']==3)echo"checked"?> value="3">За&#160;неделю</label></li>
			<li><label><input type="radio" name="advancedForm[deduce][type]"<?php if($this->data['data']['form']['deduce']['type']==4)echo"checked"?> value="4">За&#160;месяц</label></li>
			<li><label><input type="radio" name="advancedForm[deduce][type]"<?php if($this->data['data']['form']['deduce']['type']==5)echo"checked"?> value="5">За&#160;год</label></li>
			<li><label><input type="radio" id="showInterval" name="advancedForm[deduce][type]"<?php if ($this->data['data']['form']['deduce']['type']==6)echo"checked"?> value="6">За&#160;интервал</label></li>
			<?php if ($this->data['data']['form']['deduce']['type']==6):?>
				<?php $style = "style='display:block'"; $styleInput=''?>
			<?php endif; ?>
			<li <?=$style?> id="interval">от&#160;<input id="datetimepickerFrom" value="<?=$this->data['data']['form']['deduce']['interval']['from']?>" name="advancedForm[deduce][interval][from]" <?php if ($this->data['data']['form']['deduce']['type']!=6)echo"disabled"?> type="text" >&#160;до&#160;<input id="datetimepickerBefore" value="<?=$this->data['data']['form']['deduce']['interval']['before']?>" name="advancedForm[deduce][interval][before]" type="text" <?php if ($this->data['data']['form']['deduce']['type']!=6)echo"disabled"?> ></li>
		</ul>
	</td>
</tr>
<tr>
	<td>Показывать на странице</td>
	<td>
		<ul class="view_count">
			<li><label><input type="radio" name="advancedForm[view_count]" <?php if($this->data['data']['form']['view_count']==20 || !$this->data['data']['form']['view_count']) echo"checked"?> value="20">20&#160;резюме</label></li>
			<li><label><input type="radio" name="advancedForm[view_count]"<?php if($this->data['data']['form']['view_count']==50)echo"checked"?> value="50">50&#160;резюме</label></li>
			<li><label><input type="radio" name="advancedForm[view_count]"<?php if($this->data['data']['form']['view_count']==100)echo"checked"?> value="100">100&#160;резюме</label></li>
		</ul>
	</td>
</tr>
</tbody>
<tfoot>
<tr>
	<td></td>
	<td>
		<input type="submit" class="prosper-button" name="advancedForm[advancedFormSubmit]" value="Найти">
	</td>
</tr>
</tfoot>
</table>
</form>
</div>
<div class="clear"></div>
<?=$this->data['helpers']['admin_info_widget']?>
</main>