<main class="admin_control advanced">
<div class="header">
	<?=$this->data['helpers']['header']?>
</div>
<div class="left_admin_control">
	<?=$this->data['helpers']['widget_admin']?>
</div>
<div class="right_admin_control">
<header>
	<h1>Поиск&#160;резюме <span style="color:red">*Данный раздел еще дорабатывается</span></h1>
</header>
<form action="<?=BASE_URL.'/admincontrol/advancedresult'?>" class="advancedForm" method="post">
<table>
<tbody>
<tr>
	<td><label for="keywords">Ключевые слова</label></td>
	<td>
		<div class="inputKeywordsBlock">
			<span><input type="text" name="advancedForm[wordKey][input]" id="keywords" value="" title="Ключевые&#160;слова"></span>
			<span><input type="submit" class="prosper-button" name="advancedForm[advancedFormSubmit]" value="Найти"></span>
			<div>
				<span id="targetRadio">
					<span class="resumeSearchSort">Все&#160;слова</span>
					<ul class="radioBlock">
						<li><label><input type="radio" name="advancedForm[wordKey][parse]" value="allWorlds" checked>Все&#160;слова</label></li>
						<li><label><input type="radio" name="advancedForm[wordKey][parse]" value="someWorlds">Любое&#160;из&#160;слов</label></li>
						<li><label><input type="radio" name="advancedForm[wordKey][parse]" value="exactWorlds">Точная&#160;фраза</label></li>
					</ul>
				</span>
				<span id ="targetCheckbox">
					<span class="resumeSearchSort">везде</span>
					<ul class="checkboxBlock">
						<li><label><input type="checkbox" id="placeSearchAll" name="advancedForm[wordKey][placeSearch][all]" checked>везде</label></li>
						<li><label><input type="checkbox" name="advancedForm[wordKey][placeSearch][education]">в&#160;образовании</label></li>
						<li><label><input type="checkbox" name="advancedForm[wordKey][placeSearch][skills]">в&#160;ключевых&#160;навыках</label></li>
						<li>
							<label><input type="checkbox" id="workExperience" name="">в&#160;опыте&#160;работы</label>
							<ul class="childrenUl">
								<li><label><input type="checkbox" class="work-experience" name="advancedForm[wordKey][placeSearch][experience][field_activities]">в&#160;компаниях&#160;и&#160;отраслях</label></li>
								<li><label><input type="checkbox" class="work-experience" name="advancedForm[wordKey][placeSearch][experience][positions]">в&#160;должностях</label></li>
								<li><label><input type="checkbox" class="work-experience" name=advancedForm[wordKey][placeSearch][experience][functions]">в&#160;обязанностях</label></li>
							</ul>
						</li>
						<li>
							<span class="buttonCheckboxLi">OK</span>
						</li>
					</ul>
				</span>
			</div>
		</div>
	</td>
</tr>
<tr>
	<td><label for="professional_area">Профессиональная область</label></td>
	<td>
		<span class="professionalAreaLink">Любая<span class="link">Указать профобласти</span></span>
		<div id="inputProfessionalAreaBlock">
			<input type="text" name="advancedForm[professional_area][]" id="professional_area" value="">
			<h1 id="addProfessionalAreaButton" class="prosper-button">Добавить</h1>
			<h1 id="cancelProfessionalAreaButton" class="prosper-button">Отменить</h1>
			<div class="professionalAreaList"></div>
		</div>
	</td>
</tr>
<tr>
	<td><label for="city">Регион</label></td>
	<td id="containerCity">
		<input type="text" name="advancedForm[city][]" id="city" value="">
		<h1 id="addCityButton" class="prosper-button">Добавить регион</h1>
		<div class="cityBlock"></div>
	</td>
</tr>
<tr>
	<td><label for="salary">Зарплата</label></td>
	<td>
		<span class="salaryInput">
			&#160;от&#160;<input type="text" name="advancedForm[salary][from]" value="">&#160;до&#160;
			<input class="salaryInput" type="text" name="advancedForm[salary][before]" value="">
			<select name="advancedForm[salary][currency]">
				<option value="бел. руб.">бел. руб.</option>
				<option value="рос. руб.">рос. руб.</option>
				<option value="EUR">EUR</option>
				<option value="USD">USD</option>
			</select>
		</span>
		<span class="salaryInputCheckbox">
			<label><input type="checkbox" name="advancedForm[salary][show_empty]" value="false">Не&#160;показывать&#160;резюме&#160;без&#160;зарплаты</label>
		</span>
	</td>
</tr>
<tr>
	<td>Требуемый&#160;опыт&#160;работы</td>
	<td>
		<ul class="experience">
			<li><label><input type="checkbox" name="advancedForm[experience][no]" value="">Нет&#160;опыта</label></li>
			<li><label><input type="checkbox" name="advancedForm[experience][one-three]" value="">От&#160;1&#160;года&#160;до&#160;3&#160;лет</label></li>
			<li><label><input type="checkbox" name="advancedForm[experience][three-six]" value="">От&#160;3&#160;до&#160;6&#160;лет</label></li>
			<li><label><input type="checkbox" name="advancedForm[experience][six-more]" value="">Более&#160;6&#160;лет</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td><label for="education">Образование</label></td>
	<td>
		<select name="advancedForm[education][degree]" id="education">
			<option value="">Не&#160;имеет&#160;значения</option>
			<option value="Высшее">Высшее</option>
			<option value="Бакалавр">Бакалавр</option>
			<option value="Магистр">Магистр</option>
			<option value="Кандидат наук">Кандидат&#160;наук</option>
			<option value="Доктор наук">Доктор&#160;наук</option>
			<option value="Незаконченное высшее">Незаконченное&#160;высшее</option>
			<option value="Среднее">Среднее</option>
			<option value="Среднее специальное">Среднее&#160;специальное</option>
		</select>
		<div class="names_institutions">
			<span class="link">Указать названия учебных заведений</span>
			<div class="institutionsBlock">
				<p>Добавить учебное заведение</p>
				<input type="text" name="advancedForm[education][name]" disabled value="">
			</div>
		</div>
	</td>
</tr>
<tr>
	<td><label for="nationality">Гражданство</label></td>
	<td>
		<span class="linkSpan">Любая<span class="link">Указать&#160;страну</span></span>
		<div class="hideDiv">
			<p>Добавить&#160;страну</p>
			<input type="text" name="advancedForm[nationality][name]" id="nationality" disabled value="">
		</div>
	</td>
</tr>
<tr>
	<td><label for="work_permit">Разрешение на работу</label></td>
	<td>
		<span class="linkSpan">Любая<span class="link">Указать&#160;страну</span></span>
		<div class="hideDiv">
			<p>Добавить&#160;страну</p>
			<input type="text" name="advancedForm[work_permit][name]" id="work_permit" disabled value="">
		</div>
	</td>
</tr>
<tr>
	<td><label>Возраст&#160;и&#160;фотография</label></td>
	<td>
		<div class="ageInput">
			&#160;от&#160;<input type="text" name="advancedForm[age][from]" value="">&#160;до&#160;
			<input class="salaryInput" type="text" name="advancedForm[age][before]" value="">
		</div>
		<div class="ageInputCheckbox">
			<span><label><input type="checkbox" name="advancedForm[age][show_empty]" value="false">Не&#160;показывать&#160;резюме&#160;без&#160;указания&#160;возраста</label></span>
			<span><label><input type="checkbox" name="advancedForm[age][show_photo]" value="false">Только&#160;с&#160;фотографией</label></span>
		</div>
	</td>
</tr>
<tr>
	<td>Пол</td>
	<td>
		<ul class="sex">
			<li><label><input type="radio" name="advancedForm[sex]" value="" checked>Не&#160;имеет&#160;значения</label></li>
			<li><label><input type="radio" name="advancedForm[sex]" value="Мужской">Мужской</label></li>
			<li><label><input type="radio" name="advancedForm[sex]" value="Женский">Женский</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td>Тип занятости</td>
	<td>
		<ul class="employment">
			<li><label><input type="checkbox" name="advancedForm[employment][]" value="Полная занятость">Полная&#160;занятость</label></li>
			<li><label><input type="checkbox" name="advancedForm[employment][]" value="Частичная занятость">Частичная&#160;занятость</label></li>
			<li><label><input type="checkbox" name="advancedForm[employment][]" value="Проектная/Временная работа">Проектная/Временная&#160;работа</label></li>
			<li><label><input type="checkbox" name="advancedForm[employment][]" value="Волонтерство">Волонтерство</label></li>
			<li><label><input type="checkbox" name="advancedForm[employment][]" value="Стажировка">Стажировка</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td>График работы</td>
	<td>
		<ul class="schedule">
			<li><label><input type="checkbox" name="advancedForm[schedule][]" value="Полный день">Полный&#160;день</label></li>
			<li><label><input type="checkbox" name="advancedForm[schedule][]" value="Сменныйграфик">Сменный&#160;график</label></li>
			<li><label><input type="checkbox" name="advancedForm[schedule][]" value="Гибкий график">Гибкий&#160;график</label></li>
			<li><label><input type="checkbox" name="advancedForm[schedule][]" value="Удаленная работа">Удаленная&#160;работа</label></li>
			<li><label><input type="checkbox" name="advancedForm[schedule][]" value="Вахтовый метод">Вахтовый&#160;метод</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td>Знание языков</td>
	<td>
		<div id="blockLanguage">
			<ul id="languages"></ul>
			<div><span id="linkLanguage">Добавить язык</span></div>
		</div>
	</td>
</tr>
<tr>
	<td>Сортировать</td>
	<td>
		<ul class="sort">
			<li><label><input type="radio" name="advancedForm[sort]"  checked value="decrease">По&#160;убыванию&#160;зарплат</label></li>
			<li><label><input type="radio" name="advancedForm[sort]" value="increase">По&#160;возрастанию&#160;зарплаты</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td>Выводить</td>
	<td>
		<ul class="deduce">
			<li><label><input type="radio" name="advancedForm[deduce]" checked value="0">За весь период</label></li>
			<li><label><input type="radio" name="advancedForm[deduce]" value="1">За сутки</label></li>
			<li><label><input type="radio" name="advancedForm[deduce]" value="2">За последние три дня</label></li>
			<li><label><input type="radio" name="advancedForm[deduce]" value="3">За неделю</label></li>
			<li><label><input type="radio" name="advancedForm[deduce]" value="4">За месяц</label></li>
			<li><label><input type="radio" name="advancedForm[deduce]" value="5">За год</label></li>
			<li><label><input type="radio" name="advancedForm[deduce]" value="6">За интервал</label></li>
		</ul>
	</td>
</tr>
<tr>
	<td>Показывать на странице</td>
	<td>
		<ul class="deduce_count">
			<li><label><input type="radio" name="advancedForm[view_count]" checked value="20">20 резюме</label></li>
			<li><label><input type="radio" name="advancedForm[view_count]" value="50">50 резюме</label></li>
			<li><label><input type="radio" name="advancedForm[view_count]" value="100">100 резюме</label></li>
		</ul>
	</td>
</tr>
</tbody>
<tfoot>
<tr>
	<td></td>
	<td>
		<input type="submit" class="prosper-button" name="advancedForm[advancedFormSubmit]" value="Найти">
	</td>
</tr>
</tfoot>
</table>
</form>
</div>
<div class="clear"></div>
<?=$this->data['helpers']['admin_info_widget']?>
</main>