<main class="admin_control folders">
	<div class="out">
		<a href='<?=BASE_URL."/admin/out/"?>'>Выход</a>
	</div>
	<div class="clear"></div>
	<form  action='<?=BASE_URL."/admincontrol/index/search/"?>' method="get">
		<div class="search">
			<input type="search" name="search" value="<?=$this->data['data']['search']?>" placeholder="введите текст для поиска">
			<input type="submit" value="найти">
			<div class="clear"></div>
		</div>
	</form>
	<div class="left_admin_control">
		<?=$this->data['helpers']['widget_admin']?>
	</div>
	<div class="right_admin_control">
		<div class="folders_form">
			<form action='<?=BASE_URL."/admincontrol/folders"?>' method="post">
				<input type="text" name="folder" value="">
				<input type="submit" name="addFolder" value="создать">
			</form>
		</div>
		<?php if(count($this->data['data']['folders']) !== 0): ?>
			<div class="folders_list">
				<ul>
					<?php foreach($this->data['data']['folders'] as $value): ?>
						<li>
							<a href='<?=BASE_URL."/admincontrol/folders/delete/{$value['id']}"?>'><img src="<?=BASE_URL ."/public/img/delete.png"?>"></a>
							<span><?=$value['name']?></span>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php else: ?>
			<p class="no_resume">У вас нет папок</p>
		<?php endif; ?>
	</div>
	<div class="clear"></div>
</main>