<main class="admin_control">
	<div class="out">
		<a href='<?=BASE_URL."/admin/out"?>'>Выход</a>
	</div>
	<div class="clear"></div>
	<form  action='<?=BASE_URL."/admincontrol"?>' method="post">
		<div class="search">
			<input type="search" name="search_resume" value="" placeholder="введите текст для поиска...">
			<input type="submit"  name="searchResume" value="найти">
			<div class="clear"></div>
		</div>
	</form>
	<div class="left_admin_control">
		цйфвфу ывфы
		ываzxcz
		zdc
		ds
		fd
		вы
	</div>
	<div class="right_admin_control">
		<nav>
			<ul>
				<li><a href="">1</a></li>
				<li><a href="">2</a></li>
				<li><a href="">3</a></li>
				<li><a href="">4</a></li>
				<li><a href="">...</a></li>
				<li><a href="">10</a></li>
			</ul>
		</nav>
		<div class="user_id">
			<figure>
				<img src='<?=BASE_URL."/files/photo/no-photo.png"?>'>
			</figure>
			<div class="inform_user">
				<span class="salary_inform_user">10000000 бел. руб. 30 лет</span>
				<div class="name_user_inform">Тельпук Сергей Васильевич</div>
				<div class="position"><a href="">Менеджер по продажам</a></div>
				<p>
					Опыт работы<br><span>7 лет</span>
				</p>
				<p>
					Последнее место работы<br>
					<span>Региональный представитель, ведущий презентаций, июнь 2012—по настоящее время</span>
				</p>
				<p>
					ЛамаГолд, ИООО, медицина, фармацевтика, аптеки
				</p>
			</div>
			<div class="clear"></div>
		</div>

	</div>
	<div class="clear"></div>
</main>