<main class="admin_control">
	<div class="out">
		<a href='<?=BASE_URL."/admin/out/"?>'>Выход</a>
	</div>
	<div class="clear"></div>
	<form  action='<?=BASE_URL."/admincontrol/index/search/"?>' method="get">
		<div class="search">
			<input type="search" name="search" value="<?=$this->data['data']['search']?>" placeholder="введите текст для поиска">
			<input type="submit" value="найти">
			<div class="clear"></div>
		</div>
	</form>
	<div class="left_admin_control">
		<p><a href='<?=BASE_URL."/admincontrol"?>'><?=$this->data['data']['users_count']?></a></p>
		<p><a href="<?=BASE_URL."/admincontrol/unreviewed/view/no"?>">новые анкеты:<?=$this->data['data']['count_view_admin_resume']?></a></p>
	</div>
	<div class="right_admin_control">
		<nav>
			<?=$this->data['data']['pagination']?>
		</nav>
		<?php foreach($this->data['data']['users'] as $key=>$user): ?>
			<div class="user_id">
				<figure>
					<img src='<?=BASE_URL."/files/photo/{$user['photo']}"?>'>
				</figure>
				<div class="inform_user">
					<span class="salary_inform_user"><?=$user['salary']?></span>
					<div class="position"><?=$user['desired_position']?></div>
					<div class="name_user_inform"><a href="<?=BASE_URL."/index/index/id/" .$user['id']?>"><?=$user['name']?></a></div>
					<p>
						Опыт работы<br><span><?=$user['sum_experience']?></span>
					</p>
					<p>
						Последнее место работы<br>
						<span><?=$user['last_place_work']['last_position']?>, <?=$user['last_place_work']['date']?></span>
					</p>
					<p>
						<?=$user['last_place_work']['last_works']?>
					</p>
				</div>
				<div class="clear"></div>
			</div>
		<?php endforeach; ?>
		<nav>
			<?=$this->data['data']['pagination']?>
		</nav>
	</div>
	<div class="clear"></div>
</main>