<main class="admin_control">
	<div class="out">
		<a href='<?=BASE_URL."/admin/out"?>'>Выход</a>
	</div>
	<div class="clear"></div>
	<form  action='<?=BASE_URL."/admincontrol"?>' method="post">
		<div class="search">
			<input type="search" name="search" value="<?=$this->data['data']['search']?>"
			       placeholder="введите текст для поиска">
			<input type="submit"  name="searchResume" value="найти">
			<div class="clear"></div>
		</div>
	</form>
	<div class="left_admin_control">
		цйфвфу ывфы
		ываzxcz
		zdc
		ds
		fd
		вы
	</div>
	<div class="right_admin_control">
		<nav>
			<ul>
				<li><a href="">1</a></li>
				<li><a href="">2</a></li>
				<li><a href="">3</a></li>
				<li><a href="">4</a></li>
				<li><a href="">...</a></li>
				<li><a href="">10</a></li>
			</ul>
		</nav>
		<?php foreach($this->data['data']['user'] as $key=>$user): ?>
			<div class="user_id">
				<figure>
					<img src='<?=BASE_URL."/files/photo/{$user['photo']}"?>'>
				</figure>
				<div class="inform_user">
					<span class="salary_inform_user"><?=$user['salary']?></span>
					<div class="position"><?=$user['desired_position']?></div>
					<div class="name_user_inform"><a href="<?=BASE_URL."/index/index/id/" .$user['id']?>"><?=$user['name']?></a></div>
					<p>
						Опыт работы<br><span><?=$user['sum_experience']?></span>
					</p>
					<p>
						Последнее место работы<br>
						<span>Региональный представитель, ведущий презентаций, июнь 2012—по настоящее время</span>
					</p>
					<p>
						ЛамаГолд, ИООО, медицина, фармацевтика, аптеки
					</p>
				</div>
				<div class="clear"></div>
			</div>
		<?php endforeach; ?>

	</div>
	<div class="clear"></div>
</main>