<main class="admin_control managers">
	<div class="header">
		<?=$this->data['helpers']['header']?>
	</div>
	<div class="left_admin_control">
		<?=$this->data['helpers']['widget_admin']?>
	</div>
	<div class="right_admin_control">
		<div id="add_manager"><img src="<?=BASE_URL.'/public/img/manager_add.png'?>"> Добавить менеджера</div>
		<?=$this->data['helpers']['message']?>
		<div class="form_manager">
			<form id="manager_form" action='<?=BASE_URL."/admincontrol/addmanager"?>' method="post">
				<p>
					<label for="">имя</label>
					<input type="text" name="name_first" value="<?=$this->data['data']['inputs']['name_first']['value']?>">
				<div class="message"><?=$this->data['data']['inputs']['name_first']['val']['message']?></div>
				</p>
				<p>
					<label for="">логин</label>
					<input type="text" name="login_manager" value="<?=$this->data['data']['inputs']['login_manager']['value']?>">
				<div class="message"><?=$this->data['data']['inputs']['login_manager']['val']['message']?></div>
				</p>
				<p>
					<label for="">пароль</label>
					<input type="text" name="password_manager" value="<?=$this->data['data']['inputs']['password_manager']['value']?>">
				<div class="message"><?=$this->data['data']['inputs']['password_manager']['val']['message']?></div>
				</p>
				<p>
					<input type="submit" name="addManager" value="создать">
				</p>
			</form>
			<div class="clear"></div>
		</div>
		<div class="table_managers">
			<?php if(count($this->data['data']['managers']) !== 0): ?>
				<table>
					<thead>
					<tr>
						<th>№</th>
						<th>имя</th>
						<th>логин</th>
						<th>пароль</th>
						<th></th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($this->data['data']['managers'] as $key=>$manager): ?>
						<tr>
							<td><?=$key+1?></td>
							<td><?=$manager['name_first']?></td>
							<td><?=$manager['login']?></td>
							<td><?=$manager['password']?></td>
							<td><a href="<?=BASE_URL."/admincontrol/delmanager/delete/{$manager['id']}"?>"><img src="<?=BASE_URL ."/public/img/manager_delete.png"?>"</a></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			<?php else: ?>
				<p class="no_resume">У вас нет менеджеров</p>
			<?php endif; ?>
		</div>
	</div>
	<div class="clear"></div>
	<?=$this->data['helpers']['admin_info_widget']?>
</main>