<main class="admin_control">
	<div class="out">
		<a href='<?=BASE_URL."/admin/out/"?>'>Выход</a>
	</div>
	<div class="clear"></div>
	<form  action='<?=BASE_URL."/admincontrol/index/search/"?>' method="get">
		<div class="search">
			<input type="search" name="search" value="<?=$this->data['data']['search']?>" placeholder="введите текст для поиска">
			<input type="submit" value="найти">
			<div class="clear"></div>
		</div>
	</form>
	<div class="left_admin_control">
		<?=$this->data['helpers']['widget_admin']?>
	</div>
	<div class="right_admin_control">
		<?=$this->data['helpers']['message']?>
		<div class="form_manager">
			<form action='<?=BASE_URL."/admincontrol/addmanager"?>' method="post">
				<p>
					<label for="">имя</label>
					<input type="text" name="name_first" value="<?=$this->data['data']['inputs']['name_first']?>">
				</p>
				<p>
					<label for="">логин</label>
					<input type="text" name="login_manager" value="<?=$this->data['data']['inputs']['login_manager']?>">
				</p>
				<p>
					<label for="">пароль</label>
					<input type="text" name="password_manager" value="<?=$this->data['data']['inputs']['password_manager']?>">
				</p>
				<p>
					<input type="submit" name="addManager" value="создать">
				</p>
			</form>
			<div class="clear"></div>
		</div>
		<?=$this->data['helpers']['manager_count']?>
	</div>
	<div class="clear"></div>
</main>